import json
import os

DB_PATH = '/Users/steve/CODE/moana-study-projects/wordlist/wordlist-quiz/public/db/wordlist_esl.json'

new_words_data = [
    # Unit 8
    {"unit": "8.1", "word": "air pollution", "definition": "When the air becomes dirty from smoke, gases, or chemicals.", "example": "Cars and factories cause air pollution, making it harder to breathe.", "vietnamese": "Ô nhiễm không khí. (Ví dụ: Ô tô và nhà máy gây ô nhiễm không khí, làm cho việc hít thở khó khăn hơn.)"},
    {"unit": "8.1", "word": "plastic pollution", "definition": "When plastic waste harms the environment, especially in oceans and rivers.", "example": "Plastic pollution is dangerous for sea animals like turtles and fish.", "vietnamese": "Ô nhiễm nhựa. (Ví dụ: Ô nhiễm nhựa rất nguy hiểm cho các loài động vật biển như rùa và cá.)"},
    {"unit": "8.1", "word": "rising sea levels", "definition": "When the ocean water gets higher due to melting ice and climate change.", "example": "Many islands are at risk because of rising sea levels.", "vietnamese": "Mực nước biển dâng cao. (Ví dụ: Nhiều hòn đảo đang gặp nguy hiểm vì mực nước biển dâng cao.)"},
    {"unit": "8.1", "word": "melting ice caps", "definition": "When the ice at the North and South Poles melts due to global warming.", "example": "The melting ice caps are causing polar bears to lose their homes.", "vietnamese": "Băng tan ở các cực. (Ví dụ: Băng tan ở các cực đang khiến gấu Bắc cực mất đi môi trường sống của chúng.)"},
    {"unit": "8.1", "word": "rubbish", "definition": "Waste or things that are thrown away.", "example": "We should put our rubbish in the bin, not on the ground.", "vietnamese": "Rác thải. (Ví dụ: Chúng ta nên bỏ rác thải vào thùng, không nên vứt xuống đất.)"},
    {"unit": "8.1", "word": "environment", "definition": "The world around us, including trees, animals, air, and water.", "example": "We must take care of the environment to keep it clean and safe.", "vietnamese": "Môi trường. (Ví dụ: Chúng ta phải chăm sóc môi trường để giữ cho nó sạch sẽ và an toàn.)"},
    {"unit": "8.1", "word": "global warming", "definition": "When the Earth gets hotter because of pollution and gases in the air.", "example": "Global warming is causing more wildfires and extreme weather.", "vietnamese": "Nóng lên toàn cầu. (Ví dụ: Nóng lên toàn cầu đang gây ra nhiều cháy rừng và thời tiết khắc nghiệt hơn.)"},
    {"unit": "8.1", "word": "eco-friendly", "definition": "Good for the environment and not harmful to nature.", "example": "Using a reusable water bottle is an eco-friendly choice.", "vietnamese": "Thân thiện với môi trường. (Ví dụ: Sử dụng bình nước có thể lặp lại là một lựa chọn thân thiện với môi trường.)"},
    {"unit": "8.1", "word": "environmentalists", "definition": "People who work to protect the environment.", "example": "Environmentalists plant trees and clean up beaches to help nature.", "vietnamese": "Những nhà bảo vệ môi trường. (Ví dụ: Những nhà bảo vệ môi trường trồng cây và dọn dẹp bãi biển để giúp đỡ thiên nhiên.)"},

    {"unit": "8.2", "word": "non-biodegradable", "definition": "Something that does not break down naturally and stays in the environment for a long time.", "example": "Plastic bags are non-biodegradable and can last for hundreds of years.", "vietnamese": "Không thể phân hủy sinh học. (Ví dụ: Túi nhựa không thể phân hủy sinh học và có thể tồn tại trong hàng trăm năm.)"},
    {"unit": "8.2", "word": "microparticle", "definition": "A tiny piece of material, often plastic, that is too small to see easily.", "example": "Fish sometimes eat microparticles of plastic in the ocean.", "vietnamese": "Hạt vi nhựa/vi hạt. (Ví dụ: Cá đôi khi vô tình ăn các hạt vi nhựa trong đại dương.)"},
    {"unit": "8.2", "word": "medical products", "definition": "Things used for health and medicine, such as masks, gloves, and syringes.", "example": "Doctors use medical products like masks and gloves to stay safe.", "vietnamese": "Sản phẩm y tế. (Ví dụ: Bác sĩ dùng các sản phẩm y tế như khẩu trang và găng tay để giữ an toàn.)"},
    {"unit": "8.2", "word": "single use", "definition": "Something that is used only once and then thrown away.", "example": "Plastic straws are single-use items that create a lot of waste.", "vietnamese": "Dùng một lần. (Ví dụ: Ống hút nhựa là sản phẩm dùng một lần tạo ra nhiều rác thải.)"},
    {"unit": "8.2", "word": "replace", "definition": "To take something away and put something new in its place.", "example": "We should replace plastic bags with reusable ones to help the planet.", "vietnamese": "Thay thế. (Ví dụ: Chúng ta nên thay thế túi nhựa bằng loại dùng nhiều lần để bảo vệ hành tinh.)"},

    {"unit": "8.3", "word": "quiz", "definition": "A short test or game that asks questions to check knowledge.", "example": "We had a fun quiz in class today about animals.", "vietnamese": "Câu đố/bài kiểm tra ngắn. (Ví dụ: Hôm nay chúng tôi có một câu đố vui trong lớp về các loài động vật.)"},
    {"unit": "8.3", "word": "be green", "definition": "To care about and help protect the environment.", "example": "It’s important to be green and recycle plastic bottles.", "vietnamese": "Bảo vệ môi trường/sống xanh. (Ví dụ: Việc bảo vệ môi trường và tái chế chai nhựa rất quan trọng.)"},
    {"unit": "8.3", "word": "survey", "definition": "A set of questions used to collect information from people.", "example": "The teacher asked us to complete a survey about our favorite books.", "vietnamese": "Khảo sát. (Ví dụ: Giáo viên yêu cầu chúng tôi hoàn thành một khảo sát về những cuốn sách yêu thích.)"},
    {"unit": "8.3", "word": "Eco-challenges", "definition": "Activities or tasks that help protect nature and the environment.", "example": "Our school set up weekly eco-challenges to help save energy.", "vietnamese": "Thử thách sinh thái. (Ví dụ: Trường chúng tôi tổ chức các thử thách sinh thái hàng tuần để giúp tiết kiệm năng lượng.)"},

    {"unit": "8.4", "word": "Field trip", "definition": "A visit to a place outside school for learning purposes.", "example": "We went on a field trip to the science museum.", "vietnamese": "Chuyến tham quan ngoại khóa. (Ví dụ: Chúng tôi đã đi tham quan ngoại khóa tới bảo tàng khoa học.)"},
    {"unit": "8.4", "word": "theatre", "definition": "A place where people watch plays or performances.", "example": "We watched a fantastic play at the theatre last night.", "vietnamese": "Nhà hát. (Ví dụ: Chúng tôi đã xem một vở kịch tuyệt vời ở nhà hát tối qua.)"},
    {"unit": "8.4", "word": "clipboard", "definition": "A hard surface with a clip at the top, used to hold papers for writing.", "example": "The coach carried a clipboard to write down our scores.", "vietnamese": "Bìa kẹp tài liệu. (Ví dụ: Huấn luyện viên mang một chiếc bìa kẹp tài liệu để ghi điểm số của chúng tôi.)"},
    {"unit": "8.4", "word": "tiny", "definition": "Very small in size.", "example": "The baby bird was so tiny that it could fit in my hand.", "vietnamese": "Rất nhỏ bé. (Ví dụ: Lạc đà con nhỏ đến mức có thể đặt vừa trong bàn tay tôi.)"},
    {"unit": "8.4", "word": "duckling", "definition": "A baby duck.", "example": "A mother duck led her ducklings across the pond.", "vietnamese": "Vịt con. (Ví dụ: Một vịt mẹ đang dẫn đàn vịt con qua hồ.)"},
    {"unit": "8.4", "word": "reeds", "definition": "Tall, thin plants that grow near water.", "example": "The ducks hid among the reeds by the riverbank.", "vietnamese": "Cây sậy. (Ví dụ: Những con vịt ẩn mình giữa những đám sậy bên bờ sông.)"},
    {"unit": "8.4", "word": "purpose", "definition": "The reason why something is done or exists.", "example": "The purpose of the meeting was to plan our school festival.", "vietnamese": "Mục đích. (Ví dụ: Mục đích của buổi họp mặt là để lên kế hoạch cho lễ hội của trường.)"},

    {"unit": "8.5", "word": "steel", "definition": "A strong metal made from iron and carbon.", "example": "The bridge is made of strong steel to hold many cars.", "vietnamese": "Thép. (Ví dụ: Cây cầu được làm từ thép chắc chắn để tải nhiều chiếc ô tô.)"},
    {"unit": "8.5", "word": "massive", "definition": "Very big and heavy.", "example": "A massive elephant walked through the safari park.", "vietnamese": "To lớn. (Ví dụ: Một con voi to lớn đã đi bộ qua công viên hoang dã safari.)"},
    {"unit": "8.5", "word": "vast", "definition": "Extremely large in size or amount.", "example": "The ocean is so vast that you cannot see the end of it.", "vietnamese": "Rộng lớn. (Ví dụ: Đại dương rộng lớn đến nỗi bạn không thể thấy chân trời.)"},
    {"unit": "8.5", "word": "empty", "definition": "Having nothing inside.", "example": "The classroom was empty because everyone had gone home.", "vietnamese": "Trống rỗng. (Ví dụ: Lớp học trống rỗng vì mọi người đã đi về nhà.)"},
    {"unit": "8.5", "word": "deserted", "definition": "Without people; abandoned.", "example": "The old house looked deserted and spooky at night.", "vietnamese": "Vắng vẻ/Bỏ hoang. (Ví dụ: Ngôi nhà cũ trông vắng vẻ và ám ảnh vào ban đêm.)"},
    {"unit": "8.5", "word": "greenery", "definition": "Green plants and leaves.", "example": "The park was full of beautiful greenery and colorful flowers.", "vietnamese": "Cây xanh. (Ví dụ: Công viên có nhiều loại cây xanh tuyệt đẹp và hoa đầy màu sắc.)"},
    {"unit": "8.5", "word": "remote control", "definition": "A small device used to control a machine from a distance.", "example": "I used the remote control to change the TV channel.", "vietnamese": "Điều khiển từ xa. (Ví dụ: Tôi đã sử dụng điều khiển từ xa để đổi kênh.)"},
    {"unit": "8.5", "word": "shadow", "definition": "A dark shape made when something blocks the light.", "example": "My shadow looked long and tall in the afternoon sun.", "vietnamese": "Bóng râm/Bóng tối. (Ví dụ: Bóng của tôi trải dài và cao ra trong cái nắng chiều.)"},
    {"unit": "8.5", "word": "junk", "definition": "Things that are not useful and often thrown away.", "example": "We cleaned the attic and threw away a lot of junk.", "vietnamese": "Đồ bỏ đi. (Ví dụ: Chúng tôi đã dọn dẹp gác xếp và vứt đi quá nhiều đồ bỏ đi.)"},
    {"unit": "8.5", "word": "electronic", "definition": "Using electricity and small circuits to work.", "example": "My new electronic watch tells me the time and tracks my steps.", "vietnamese": "Điện tử. (Ví dụ: Đồng hồ điện tử của tôi báo giờ và theo dõi bước chân tôi.)"},
    {"unit": "8.5", "word": "dizzy", "definition": "Feeling like everything is spinning and you might fall.", "example": "Spinning too fast made me feel dizzy.", "vietnamese": "Chóng mặt. (Ví dụ: Quay quá nhanh khiến tôi cảm thấy hoa mắt chóng mặt.)"},
    {"unit": "8.5", "word": "swirling", "definition": "Moving in circles or a twisting motion.", "example": "The wind sent the autumn leaves swirling through the air.", "vietnamese": "Xoáy/Cuộn. (Ví dụ: Gió cuốn những lá thu xoáy trong không trung.)"},
    {"unit": "8.5", "word": "emotion", "definition": "A strong feeling like happiness, sadness, or anger.", "example": "She felt a strong emotion of happiness when she won the race.", "vietnamese": "Cảm xúc. (Ví dụ: Cô cảm thấy có một cảm xúc mãnh liệt khi giành cúp.)"},

    # Unit 9
    {"unit": "9.1", "word": "make a den", "definition": "To build a small, hidden space or shelter for playing.", "example": "The children used blankets and chairs to make a den in the living room.", "vietnamese": "Làm một cái hang/tổ. (Ví dụ: Các em nhỏ dùng chăn và ghế để làm một cái hang trong phòng khách.)"},
    {"unit": "9.1", "word": "make friends", "definition": "To form beneficial relationships with people.", "example": "She was happy to make friends at her new school.", "vietnamese": "Kết bạn. (Ví dụ: Cô bé rất vui khi kết bạn ở trường mới.)"},
    {"unit": "9.1", "word": "bake a cake", "definition": "To cook a sweet dessert in an oven.", "example": "We decided to bake a cake for my mom's birthday.", "vietnamese": "Nướng bánh. (Ví dụ: Chúng tôi quyết định nướng bánh cho sinh nhật của mẹ.)"},
    {"unit": "9.1", "word": "go rock climbing", "definition": "To climb up or across natural rock formations or artificial rock walls.", "example": "They went to the mountains to go rock climbing.", "vietnamese": "Leo núi đá. (Ví dụ: Họ đã đến những ngọn núi để đi leo núi đá.)"},
    {"unit": "9.1", "word": "on a zip wire", "definition": "Riding a cable suspended between two points, usually for fun or transportation.", "example": "The kids were excited to slide down on a zip wire.", "vietnamese": "Trượt qua cáp. (Ví dụ: Bọn trẻ háo hức khi trượt vào dây treo cáp.)"},
    {"unit": "9.1", "word": "explore a new place", "definition": "To travel to a place you have never been to learn about it.", "example": "During the holidays, we love to explore a new place.", "vietnamese": "Khám phá vùng đất mới. (Ví dụ: Khi nghỉ lễ, chúng tôi thích dạo chơi tìm hiểu về điều mới.)"},
    {"unit": "9.1", "word": "design a t-shirt", "definition": "To create a unique pattern or image for a t-shirt.", "example": "He bought some fabric markers to design a t-shirt for his team.", "vietnamese": "Thiết kế một chiếc áo phông. (Ví dụ: Cậu ấy đã mua bút mực làm đồ cho đội.)"},

    {"unit": "9.2", "word": "web address/URL", "definition": "The unique address of a website that you type into the browser to visit a page. eg: www.freetheanimals.com", "example": "Type the web address (URL) into the address bar to visit the website.", "vietnamese": "Địa chỉ web/URL. (Ví dụ: Nhập địa chỉ web (URL) vào thanh địa chỉ để truy cập trang web.)"},
    {"unit": "9.2", "word": "refresh", "definition": "To reload a webpage to see new or updated content.", "example": "If the webpage is not loading, click the refresh button to try again.", "vietnamese": "Làm mới. (Ví dụ: Mọi người nhấp vào nút làm mới nếu trang web không tải.)"},
    {"unit": "9.2", "word": "bookmark star", "definition": "A button in a web browser that lets you save a website so you can find it easily later.", "example": "I clicked the bookmark star to save my favorite website for later.", "vietnamese": "Ngôi sao đánh dấu. (Ví dụ: Tôi đã nhấp vào ngôi sao đánh dấu trang để lưu trang web xem sau.)"},
    {"unit": "9.2", "word": "address bar", "definition": "The space at the top of a web browser where you type a website’s URL.", "example": "You can type ‘www.cambridge.org’ in the address bar to find learning resources.", "vietnamese": "Thanh địa chỉ. (Ví dụ: Bạn có thể nhập địa chỉ URL vào đây để tìm nơi học tập.)"},
    {"unit": "9.2", "word": "minimise", "definition": "To make a window smaller so it doesn’t take up the screen but is still open.", "example": "I minimised the window to see my desktop.", "vietnamese": "Thu nhỏ (cửa sổ). (Ví dụ: Tôi thu nhỏ cửa sổ trình duyệt xuống gốc màn hình.)"},
    {"unit": "9.2", "word": "search engine", "definition": "A website like Google or Bing that helps you find information on the internet.", "example": "Google is a popular search engine that helps us find information online.", "vietnamese": "Công cụ tìm kiếm. (Ví dụ: Google là một công cụ tìm kiếm giúp chúng ta dễ dàng kiếm ra bất cứ thông tin mạng nào.)"},
    {"unit": "9.2", "word": "go forward", "definition": "A button in a web browser that takes you to the next page you visited after going back.", "example": "I clicked ‘go forward’ to return to the page I was just on.", "vietnamese": "Chuyển tiếp/Đi tiếp. (Ví dụ: Click chuột sẽ khiến nó được quay về trang khi bạn muốn tới nơi chưa có.)"},
    {"unit": "9.2", "word": "go back", "definition": "A button that takes you to the last webpage you visited.", "example": "If you make a mistake, just click ‘go back’ to return to the previous page.", "vietnamese": "Trở lại. (Ví dụ: Cậu ấy đã nhấn trở lại để trở về lại các trang đã theo dõi trước kia.)"},
    {"unit": "9.2", "word": "friendship bracelets", "definition": "Colorful bracelets made of thread or beads, given to friends as a symbol of friendship.", "example": "My best friend and I made matching friendship bracelets in different colors.", "vietnamese": "Vòng tay tình bạn. (Ví dụ: Tôi và cô bạn đã làm ra vô số vòng tay tình thương.)"},
    {"unit": "9.2", "word": "pet rocks", "definition": "A fun toy where people keep decorated rocks as pretend pets.", "example": "My pet rock has googly eyes and a tiny painted smile.", "vietnamese": "Đá thú cưng. (Ví dụ: Hòn đá của em nó thực chất có cái miệnh cong cong ở phía dưới.)"},
    {"unit": "9.2", "word": "wall painting", "definition": "A picture or artwork painted directly onto a wall, like a mural.", "example": "The wall painting in our school shows a beautiful picture of the ocean.", "vietnamese": "Mỹ thuật trên tường. (Ví dụ: Cả bức tường ở căn biệt thự có các nét nghệ thuật đẹp mê hồ tựa như cảnh đại dương.)"},
    {"unit": "9.2", "word": "survive in the wild", "definition": "To live outdoors without modern tools by finding food, water, and shelter.", "example": "To survive in the wild, you need to find clean water and build a shelter.", "vietnamese": "Sống sót nơi hoang dã. (Ví dụ: Rất cần thiết việc dùng khả năng sống tự cung tự cấp và ẩn náu khi đi lạc vào rừng rú hoang sơ.)"},
    {"unit": "9.2", "word": "wildflowers", "definition": "Flowers that grow naturally without being planted by people.", "example": "We saw bright yellow wildflowers growing near the river.", "vietnamese": "Hoa dại. (Ví dụ: Dọc lối mòn tự dưng có thật nhiều khóm hoa dại xinh xắn.)"},
    {"unit": "9.2", "word": "wildlife", "definition": "Animals that live in nature without human care, like birds, deer, or foxes.", "example": "The safari park is home to many types of wildlife, including lions and giraffes.", "vietnamese": "Thế giới hoang dã/Động vật tự nhiên. (Ví dụ: Những sinh vật ấy luôn có ý thức cao vì không bị kiểm soát như trong công viên sinh tồn.)"},
    {"unit": "9.2", "word": "nature trail", "definition": "A walking path in a natural area, like a forest or park, where people can explore and learn about plants and animals.", "example": "We followed the nature trail through the forest and saw birds and squirrels.", "vietnamese": "Đường mòn trong thế giới thiên nhiên. (Ví dụ: Lối nhỏ đưa mọi người qua được muôn vàn những thử thách thú vị trong rừng cây rậm ngút ngàn.)"},
    {"unit": "9.2", "word": "campfire", "definition": "A fire built outdoors for warmth, cooking, or storytelling while camping.", "example": "We roasted marshmallows over the campfire and told funny stories.", "vietnamese": "Lửa trại. (Ví dụ: Đêm xuống lửa trại cháy rực sưởi ấm được các thành viên trong khu lều chung.)"},

    {"unit": "9.3", "word": "Torch", "definition": "A handheld light powered by batteries, used in the dark.", "example": "I used my torch to see inside the dark tent at night.", "vietnamese": "Đèn pin. (Ví dụ: Nó bật đèn pin cho tôi soi xem có rơi mất gì không khi đêm về buông phủ lên bãi cỏ rộng.)"},
    {"unit": "9.3", "word": "waterproof jacket", "definition": "A jacket that keeps you dry in the rain.", "example": "She wore a waterproof jacket to stay dry in the rain.", "vietnamese": "Áo khoác chống thấm nước. (Ví dụ: Bất cứ lúc trời chuyển thu đều đặn sắm mua cái áo chống nước tránh cơn giông rào.)"},
    {"unit": "9.3", "word": "sleeping bag", "definition": "A warm, zip-up bag used for sleeping outdoors or while camping.", "example": "I zipped up my sleeping bag to keep warm while camping.", "vietnamese": "Túi ngủ. (Ví dụ: Em nó trùm kín mít nằm thu lô dưới lớp túi ấm áp ban đêm.)"},
    {"unit": "9.3", "word": "Sweatshirt", "definition": "A warm, long-sleeved shirt, often made of soft fabric.", "example": "He put on a sweatshirt because it was cold outside.", "vietnamese": "Áo len / nỉ thun. (Ví dụ: Chiếc áo làm cơ thể dễ chịu hơn khi vận động hoặc luyện thanh vào hôm trời hạ nhiệt độ.)"},
    {"unit": "9.3", "word": "sun cream", "definition": "A lotion that protects your skin from sunburn.", "example": "Don't forget to apply sun cream before going to the beach!", "vietnamese": "Kem chống nắng. (Ví dụ: Nhớ kĩ sử dụng khi chạy trên bãi cát nóng mà chưa mặc áo để ngừa bỏng rát.)"},
    {"unit": "9.3", "word": "tracksuit bottoms", "definition": "Comfortable, loose-fitting trousers often worn for sports or relaxing.", "example": "I wear tracksuit bottoms when I go jogging in the park.", "vietnamese": "Quần bo ống phần dưới ống chân. (Ví dụ: Chiếc quần làm bộ đầm khỏe mạnh mang tới cho con người cảm thấy gọn và thể chất.)"},
    {"unit": "9.3", "word": "sunglasses", "definition": "Glasses with dark lenses that protect your eyes from the sun.", "example": "She put on her sunglasses because the sun was too bright.", "vietnamese": "Kính siêu ngầu/Kính râm chống nắng. (Ví dụ: Không có cặp kính kia thì có nguy cơ mù tức thì với cường độ mặt trời như nay.)"},
    {"unit": "9.3", "word": "cap", "definition": "A type of hat with a curved front to protect your face from the sun.", "example": "He wore a cap to protect his face from the sun.", "vietnamese": "Nón mũ mềm. (Ví dụ: Mẫu nón của các tay golf khá được yêu chuộng vào thời tiêt nóng bức ngộp ngạt.)"},
    {"unit": "9.3", "word": "backpack", "definition": "A bag carried on the back, used for school, travel, or hiking.", "example": "I packed my books and lunch in my backpack before school.", "vietnamese": "Cặp bị sau lưng/Balo đa tác vụ. (Ví dụ: Chiếc ba lô theo tôi lên ngàn, xướng ca trên dọc đường tìm lý tưởng hoài niệm xa vơi.)"},
    {"unit": "9.3", "word": "tent", "definition": "A shelter made of fabric, used for sleeping outdoors.", "example": "We set up our tent near the lake for the night.", "vietnamese": "Lều trại chòi rạp dựng tạm. (Ví dụ: Quanh khu vục đền rất cấm hành vi giăng lều không được sự xin cho phép, do có nhiều quy chế luật lễ riêng biệt.)"},
    {"unit": "9.3", "word": "insect repellent", "definition": "A spray or lotion that keeps insects like mosquitoes away.", "example": "I sprayed insect repellent on my arms to keep mosquitoes away.", "vietnamese": "Đồ / hóa chất kìm hăm mùi và gây xua lùa côn trùng. (Ví dụ: Tránh việc nhiễm phong hàn, sốt xuất huyết thì cần trang bị chai thuốc thoa để con sâu gián bỏ màng đi.)"},
    {"unit": "9.3", "word": "rope walking", "definition": "A balancing activity where you walk along a rope, often used in adventure parks.", "example": "Rope walking requires a lot of balance and focus.", "vietnamese": "Giữ đu bước vững qua dây thừng thắt nối. (Ví dụ: Thăng bằng trên độ cao như thế chính là tuyệt kỹ đỉnh cao cho sinh mồ hôi ướt sủng cả tấm lưng tòng đơ.)"},
    {"unit": "9.3", "word": "trekking", "definition": "A long and difficult walk, usually in the mountains or countryside.", "example": "Trekking in the mountains can be tiring but exciting.", "vietnamese": "Du ngoạn, tản bộ địa hình qua vùng thảm khu hoang dã để xả xì trét và đắm trong cái yên tịnh của thiên hương. (Ví dụ: Cả bọn thích chuyến này ghê gớm!)"},
    {"unit": "9.3", "word": "sightseeing", "definition": "Visiting famous places and attractions while traveling.", "example": "During our trip, we went sightseeing and visited many famous places.", "vietnamese": "Đi lại khám phá những địa điểm thắng cảnh nức tiếng. (Ví dụ: Có thể nói đó là niềm vinh hạnh tham quan tận mắt những mỹ cảnh trên không trung xa mù.)"},

    {"unit": "9.4", "word": "date of birth", "definition": "The day, month, and year when a person was born.", "example": "Please write your date of birth on the form.", "vietnamese": "Năm sinh năm đẻ theo thời gian lịch. (Ví dụ: Họ đã phải chứng minh ra nó khớp với tài liệu mới có thể lãnh thẻ.)"},
    {"unit": "9.4", "word": "guest", "definition": "A person invited to stay at a place or attend an event.", "example": "We have a guest staying at our house this weekend.", "vietnamese": "Khách, vị khách mời nồng hẫu và chu đáo. (Ví dụ: Khách nào cũng phải nể gia quy thôi, dù đối đãi cách mấy mà sai kẽ cũng phải trách phạt.)"},
    {"unit": "9.4", "word": "passport number", "definition": "A special number on a passport used to identify a traveler.", "example": "You need to write your passport number on the travel form.", "vietnamese": "Căn cước số theo thông tin hộ chiếu lưu loát công nghệ. (Ví dụ: Họ từ chối nhận nếu mã số hộ chiếu đã bị nhòa hay không hiển thị chữ cho kĩ.)"},
    {"unit": "9.4", "word": "refreshment", "definition": "A small drink or snack to make you feel refreshed.", "example": "After the long walk, we stopped for some refreshments.", "vietnamese": "Món lót dạ. (Ví dụ: Cái bánh lót dạ kèm một ngụm trà mát lạnh thì không còn gì ngon cho bằng.)"},
    {"unit": "9.4", "word": "smooties", "definition": "A thick, blended drink made of fruit, milk, or yogurt.", "example": "I love drinking smoothies made with fresh strawberries and bananas.", "vietnamese": "Thức uống dạng lỏng sệt được làm từ pha xay hoa. (Ví dụ: Sinh tố bơ thơm lừng lan mâm trên bát cạn.)"},
    {"unit": "9.4", "word": "craft", "definition": "An activity where you make things with your hands, like painting or making paper models.", "example": "We made beautiful paper flowers in our craft lesson.", "vietnamese": "Phần kỹ xảo chế tạo đồ lưu niệm thủ công. (Ví dụ: Đứa trẻ luôn giỏi môn nắn sáp qua tay mà tạo được chim bằng đất.)"},
    {"unit": "9.4", "word": "persuasive", "definition": "Able to make people agree with you or do something through convincing words.", "example": "She gave a persuasive speech about why we should recycle more.", "vietnamese": "Diễn dịch lưu loác và thu hút nhằm biến lý kiến trở thành thật trong óc người ta. (Ví dụ: Nàng ta lừa dối siêu hạng qua kĩ năng giao tiếp khuyên dỗ.)"},
    {"unit": "9.4", "word": "school grounds", "definition": "The area around a school, including buildings, fields, and playgrounds.", "example": "Students are not allowed to leave the school grounds during lunchtime.", "vietnamese": "Cơ ngơi trong trường. (Ví dụ: Ai cố vi phạm nội quy của trường thì đều bị phát trực ban quét khắp mọi ngách.)"},
    {"unit": "9.4", "word": "compliment", "definition": "A nice thing you say to someone to make them feel good.", "example": "She gave me a nice compliment about my new haircut.", "vietnamese": "Ngôn ngữ khen lấy lòng mang tính thiện tâm. (Ví dụ: Đừng quá giả vờ rồi lại dành lời nịnh bợ giả hoạt!)"},

    {"unit": "9.5", "word": "Nervous", "definition": "Feeling worried or scared about something.", "example": "I felt nervous before my big test.", "vietnamese": "Hớt hải, hồi lòng vì run hụt. (Ví dụ: Cái đó thực sự làm cho bạn ấy cảm mến với bài hát bị lỗi nốt hơn.)"},
    {"unit": "9.5", "word": "Upset", "definition": "Feeling sad or annoyed about something.", "example": "He was upset because he lost his favorite toy.", "vietnamese": "Thất vị, nổi cơn thịnh nộ khó ưa mà cứ phàn gắt. (Ví dụ: Chuyện kia như thể khiến sự khéo cư xử của gã tiêu tùng.)"},
    {"unit": "9.5", "word": "sick/funny", "definition": "Feeling unwell or strange in your stomach.", "example": "I ate too much ice cream and now I feel a bit sick/funny.", "vietnamese": "Buồn cồn ruột cành cành khó bề kiềm hãm cơn nhợn ói. (Ví dụ: Mẹ nó vội mang túi hứng nước ói để tở cho mau hết chứng ọc sữa kia.)"},
    {"unit": "9.5", "word": "admit", "definition": "To say that something is true, even if it is difficult to say.", "example": "He had to admit that he forgot to do his homework.", "vietnamese": "Thấy khó những buộc đành thú lỗi để khỏi bị khui mòi. (Ví dụ: Cậu ta nhanh chóng bị lộ đuôi do thừa nhận sai phạm qua vài lời biện bạch sơ suất.)"},
    {"unit": "9.5", "word": "support", "definition": "To help or encourage someone.", "example": "My friends support me when I feel sad.", "vietnamese": "Giúp công hoặc tinh thần sức lực bằng vai. (Ví dụ: Nhà nào mà chả có cô em phụ lau nhà mồi sáng kia!)"},
    {"unit": "9.5", "word": "advice", "definition": "Helpful suggestions or ideas given to someone.", "example": "My teacher gave me good advice on how to improve my writing.", "vietnamese": "Quà tặng là những cái nói hay làm ngọn sáng chỉ nẻo. (Ví dụ: Tuy không cho tui tiền nhưng bạn đã cho tui chỉ dẫn tận tình.)"},
    {"unit": "9.5", "word": "actually", "definition": "A word used to show the truth or to correct a mistake.", "example": "I thought the test was tomorrow, but actually, it’s today!", "vietnamese": "Vậy thì đúng ra / thì lại hóa ra lại là. (Ví dụ: Trông thế đấy nhưng mà cuối cùng lại vậy!)"},
    {"unit": "9.5", "word": "pile", "definition": "A group of things stacked on top of each other.", "example": "There was a big pile of books on my desk.", "vietnamese": "Đống sếp đầy từng thúng lớp này đổ qua lớp khác. (Ví dụ: Nhìn vô là thấy lười do cái ngọn kia chả có ai quét tước nào mà.)"},
    {"unit": "9.5", "word": "football season", "definition": "The time of year when football matches are played regularly.", "example": "Football season starts in September, and I can't wait to watch the matches!", "vietnamese": "Hội thời lễ đấu giành những màn đi bóng hay đẹp trong khung giờ thời vụ giải banh. (Ví dụ: Một giải lớn của Nam phi vừa được đón rồng trong màn biểu khánh cực cháy bỏng!)"}
]

with open(DB_PATH, 'r', encoding='utf-8') as f:
    existing_db = json.load(f)

# Keep track of existing words for case-insensitive duplicate check
existing_words = {entry['word'].lower() for entry in existing_db}

# Filter out duplicates
new_entries = []
for entry in new_words_data:
    if entry['word'].lower() not in existing_words:
        new_entries.append(entry)
        existing_words.add(entry['word'].lower())

if new_entries:
    existing_db.extend(new_entries)
    with open(DB_PATH, 'w', encoding='utf-8') as f:
        json.dump(existing_db, f, indent=2, ensure_ascii=False)
    print(f"Added {len(new_entries)} new words to ESL database.")
else:
    print("No new words to add - all are duplicates.")
