export const actionFreezeData = [
  // INTERRUPTION (14 items)
  {
    id: 'freeze-interruption-001', game: 'actionFreezeDetective',
    sentence: 'I ___ TV when the phone rang.', clueText: 'when',
    answer: 'was watching', options: ['watched', 'was watching', 'were watching', 'am watching'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was happening when the interruption came?',
    meaningHint: 'Watching TV is the long background action.',
    formHint: 'Use was/were + V-ing for the long action. I uses was.',
    explanation: 'When is the clue. The long action was watching TV, so use was watching.',
    confusionTargets: ['watched', 'were watching'],
    distractorRationale: { 'watched': 'Watched is a short action. Watching TV takes a long time.', 'were watching': 'Use was with I.' },
    shapeCode: { subject: 'I', auxiliary: 'was', verbPhrase: 'watching' },
    tags: ['past_continuous', 'interruption', 'when'], difficulty: 1
  },
  {
    id: 'freeze-interruption-002', game: 'actionFreezeDetective',
    sentence: 'They ___ dinner when the lights went out.', clueText: 'when',
    answer: 'were eating', options: ['ate', 'was eating', 'were eating', 'eat'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was happening before the lights went out?',
    meaningHint: 'Eating dinner is the long action that got interrupted.',
    formHint: 'Use was/were + V-ing. They uses were.',
    explanation: 'When is the clue. The long action was eating dinner, so use were eating.',
    confusionTargets: ['ate', 'was eating'],
    distractorRationale: { 'ate': 'Eating dinner takes a long time, so use were eating.', 'was eating': 'Use were with They.' },
    shapeCode: { subject: 'They', auxiliary: 'were', verbPhrase: 'eating' },
    tags: ['past_continuous', 'interruption', 'subject_agreement'], difficulty: 1
  },
  {
    id: 'freeze-interruption-003', game: 'actionFreezeDetective',
    sentence: 'You ___ too fast when the police stopped you.', clueText: 'when',
    answer: 'were driving', options: ['drove', 'was driving', 'were driving', 'drive'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What long action was happening?',
    meaningHint: 'Driving is the long action that got stopped.',
    formHint: 'Use was/were + V-ing. You uses were.',
    explanation: 'When is the clue. The driving was the long action, so use were driving.',
    confusionTargets: ['drove', 'was driving'],
    distractorRationale: { 'drove': 'Driving takes a long time. Use were driving.', 'was driving': 'Use were with You.' },
    shapeCode: { subject: 'You', auxiliary: 'were', verbPhrase: 'driving' },
    tags: ['past_continuous', 'interruption', 'subject_agreement'], difficulty: 2
  },
  {
    id: 'freeze-interruption-004', game: 'actionFreezeDetective',
    sentence: 'The dog ___ loudly when someone knocked on the door.', clueText: 'when',
    answer: 'was barking', options: ['barked', 'was barking', 'were barking', 'barks'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was happening before the knock?',
    meaningHint: 'Barking is the long background action.',
    formHint: 'Use was/were + V-ing. The dog is singular, so use was.',
    explanation: 'When is the clue. The long action was barking, so use was barking.',
    confusionTargets: ['barked', 'were barking'],
    distractorRationale: { 'barked': 'Barking loudly takes a long time. Use was barking.', 'were barking': 'The dog is singular, so use was.' },
    shapeCode: { subject: 'The dog', auxiliary: 'was', verbPhrase: 'barking' },
    tags: ['past_continuous', 'interruption'], difficulty: 1
  },
  {
    id: 'freeze-interruption-005', game: 'actionFreezeDetective',
    sentence: 'We ___ for the bus when it started to snow.', clueText: 'when',
    answer: 'were waiting', options: ['waited', 'was waiting', 'were waiting', 'wait'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was the long action?',
    meaningHint: 'Waiting is a long action.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'When is the clue. The long action was waiting, so use were waiting.',
    confusionTargets: ['waited', 'was waiting'],
    distractorRationale: { 'waited': 'Waiting takes a long time. Use were waiting.', 'was waiting': 'Use were with We.' },
    shapeCode: { subject: 'We', auxiliary: 'were', verbPhrase: 'waiting' },
    tags: ['past_continuous', 'interruption', 'subject_agreement'], difficulty: 1
  },
  {
    id: 'freeze-interruption-006', game: 'actionFreezeDetective',
    sentence: 'She ___ her hair when the power went out.', clueText: 'when',
    answer: 'was drying', options: ['dried', 'was drying', 'were drying', 'dries'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was happening when the power went out?',
    meaningHint: 'Drying hair is the long action that got interrupted.',
    formHint: 'Use was/were + V-ing. She uses was.',
    explanation: 'When is the clue. Drying hair is a long action, so use was drying.',
    confusionTargets: ['dried', 'were drying'],
    distractorRationale: { 'dried': 'Drying takes a long time. Use was drying.', 'were drying': 'Use was with She.' },
    shapeCode: { subject: 'She', auxiliary: 'was', verbPhrase: 'drying' },
    tags: ['past_continuous', 'interruption'], difficulty: 1
  },
  {
    id: 'freeze-interruption-007', game: 'actionFreezeDetective',
    sentence: 'My friends ___ a movie when I arrived.', clueText: 'when',
    answer: 'were watching', options: ['watched', 'was watching', 'were watching', 'are watching'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What were they doing before I arrived?',
    meaningHint: 'Watching a movie is the long action.',
    formHint: 'Use was/were + V-ing. Friends is plural, so use were.',
    explanation: 'When is the clue. Watching a movie is a long action, so use were watching.',
    confusionTargets: ['watched', 'was watching'],
    distractorRationale: { 'watched': 'Watching takes a long time. Use were watching.', 'was watching': 'Friends is plural, so use were.' },
    shapeCode: { subject: 'My friends', auxiliary: 'were', verbPhrase: 'watching' },
    tags: ['past_continuous', 'subject_agreement', 'interruption'], difficulty: 2
  },
  {
    id: 'freeze-interruption-008', game: 'actionFreezeDetective',
    sentence: 'The baby started crying while they ___ outside.', clueText: 'while',
    answer: 'were talking', options: ['talked', 'was talking', 'were talking', 'are talking'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was the background action?',
    meaningHint: 'Talking is the long action happening at the same time.',
    formHint: 'Use was/were + V-ing. They uses were.',
    explanation: 'While is the clue. The long action was talking, so use were talking.',
    confusionTargets: ['talked', 'was talking'],
    distractorRationale: { 'talked': 'While shows a long action. Use were talking.', 'was talking': 'Use were with They.' },
    shapeCode: { subject: 'they', auxiliary: 'were', verbPhrase: 'talking' },
    tags: ['past_continuous', 'while', 'subject_agreement'], difficulty: 1
  },
  {
    id: 'freeze-interruption-009', game: 'actionFreezeDetective',
    sentence: 'I saw an accident while I ___ my car.', clueText: 'while',
    answer: 'was driving', options: ['drove', 'was driving', 'were driving', 'am driving'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was the long action?',
    meaningHint: 'Driving is the long background action.',
    formHint: 'Use was/were + V-ing. I uses was.',
    explanation: 'While is the clue. Driving is the long action, so use was driving.',
    confusionTargets: ['drove', 'were driving'],
    distractorRationale: { 'drove': 'Driving takes a long time. Use was driving.', 'were driving': 'Use was with I.' },
    shapeCode: { subject: 'I', auxiliary: 'was', verbPhrase: 'driving' },
    tags: ['past_continuous', 'while'], difficulty: 1
  },
  {
    id: 'freeze-interruption-010', game: 'actionFreezeDetective',
    sentence: 'He broke his leg while he ___ football.', clueText: 'while',
    answer: 'was playing', options: ['played', 'was playing', 'were playing', 'is playing'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What long action was happening?',
    meaningHint: 'Playing football was the long action that got interrupted.',
    formHint: 'Use was/were + V-ing. He uses was.',
    explanation: 'While is the clue. Playing football is a long action, so use was playing.',
    confusionTargets: ['played', 'were playing'],
    distractorRationale: { 'played': 'Playing takes a long time. Use was playing.', 'were playing': 'Use was with He.' },
    shapeCode: { subject: 'he', auxiliary: 'was', verbPhrase: 'playing' },
    tags: ['past_continuous', 'while', 'interruption'], difficulty: 1
  },
  {
    id: 'freeze-interruption-011', game: 'actionFreezeDetective',
    sentence: 'I dropped my keys while I ___ to the bus stop.', clueText: 'while',
    answer: 'was walking', options: ['walked', 'was walking', 'were walking', 'am walking'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was the background action?',
    meaningHint: 'Walking was the long action happening when the keys dropped.',
    formHint: 'Use was/were + V-ing. I uses was.',
    explanation: 'While is the clue. Walking is a long action, so use was walking.',
    confusionTargets: ['walked', 'were walking'],
    distractorRationale: { 'walked': 'Walking is a long action. Use was walking.', 'were walking': 'Use was with I.' },
    shapeCode: { subject: 'I', auxiliary: 'was', verbPhrase: 'walking' },
    tags: ['past_continuous', 'interruption', 'while'], difficulty: 1
  },
  {
    id: 'freeze-interruption-012', game: 'actionFreezeDetective',
    sentence: 'They found a coin while they ___ in the park.', clueText: 'while',
    answer: 'were walking', options: ['walked', 'was walking', 'were walking', 'are walking'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What long action were they doing?',
    meaningHint: 'Walking in the park is the long action.',
    formHint: 'Use was/were + V-ing. They uses were.',
    explanation: 'While is the clue. Walking is a long action, so use were walking.',
    confusionTargets: ['walked', 'was walking'],
    distractorRationale: { 'walked': 'Walking takes a long time. Use were walking.', 'was walking': 'Use were with They.' },
    shapeCode: { subject: 'they', auxiliary: 'were', verbPhrase: 'walking' },
    tags: ['past_continuous', 'while', 'interruption'], difficulty: 1
  },
  {
    id: 'freeze-interruption-013', game: 'actionFreezeDetective',
    sentence: 'The phone rang while he ___ a shower.', clueText: 'while',
    answer: 'was taking', options: ['took', 'was taking', 'were taking', 'is taking'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was happening when the phone rang?',
    meaningHint: 'Taking a shower is the long action.',
    formHint: 'Use was/were + V-ing. He uses was.',
    explanation: 'While is the clue. Taking a shower is a long action, so use was taking.',
    confusionTargets: ['took', 'were taking'],
    distractorRationale: { 'took': 'Taking a shower takes a long time. Use was taking.', 'were taking': 'Use was with He.' },
    shapeCode: { subject: 'he', auxiliary: 'was', verbPhrase: 'taking' },
    tags: ['past_continuous', 'while', 'interruption'], difficulty: 1
  },
  {
    id: 'freeze-interruption-014', game: 'actionFreezeDetective',
    sentence: 'A bird flew in while we ___ dinner.', clueText: 'while',
    answer: 'were having', options: ['had', 'was having', 'were having', 'are having'],
    scenario: 'interruption', scenarioLabel: 'Interruption',
    clueQuestion: 'What was the long background action?',
    meaningHint: 'Having dinner is the long action that got interrupted.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'While is the clue. Having dinner is a long action, so use were having.',
    confusionTargets: ['had', 'was having'],
    distractorRationale: { 'had': 'Having dinner takes a long time. Use were having.', 'was having': 'Use were with We.' },
    shapeCode: { subject: 'we', auxiliary: 'were', verbPhrase: 'having' },
    tags: ['past_continuous', 'while', 'interruption'], difficulty: 1
  },

  // PARALLEL ACTIONS (14 items)
  {
    id: 'freeze-parallel-001', game: 'actionFreezeDetective',
    sentence: 'While we ___, it started to rain.', clueText: 'While',
    answer: 'were playing', options: ['played', 'were playing', 'was playing', 'are playing'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'What long action was happening?',
    meaningHint: 'While shows a long background action.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'While is the clue. Playing is a long action, so use were playing.',
    confusionTargets: ['played', 'was playing'],
    distractorRationale: { 'played': 'While shows a long action. Use were playing.', 'was playing': 'Use were with We.' },
    shapeCode: { subject: 'we', auxiliary: 'were', verbPhrase: 'playing' },
    tags: ['past_continuous', 'while', 'subject_agreement'], difficulty: 1
  },
  {
    id: 'freeze-parallel-002', game: 'actionFreezeDetective',
    sentence: 'While he ___ a book, his sister was listening to music.', clueText: 'While',
    answer: 'was reading', options: ['read', 'was reading', 'were reading', 'reads'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Were there two long actions at the same time?',
    meaningHint: 'Reading and listening were happening at the same time.',
    formHint: 'Use was/were + V-ing. He uses was.',
    explanation: 'While is the clue. Two long actions were happening at the same time, so use was reading.',
    confusionTargets: ['read', 'were reading'],
    distractorRationale: { 'read': 'Reading takes a long time. Use was reading.', 'were reading': 'Use was with he.' },
    shapeCode: { subject: 'he', auxiliary: 'was', verbPhrase: 'reading' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 2
  },
  {
    id: 'freeze-parallel-003', game: 'actionFreezeDetective',
    sentence: 'While the teacher ___, the students were taking notes.', clueText: 'While',
    answer: 'was speaking', options: ['spoke', 'was speaking', 'were speaking', 'speaks'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'What were the two long actions?',
    meaningHint: 'Speaking and taking notes happened at the same time.',
    formHint: 'Use was/were + V-ing. Teacher is singular, so use was.',
    explanation: 'While is the clue. Speaking is a long action happening at the same time, so use was speaking.',
    confusionTargets: ['spoke', 'were speaking'],
    distractorRationale: { 'spoke': 'Speaking is a long action. Use was speaking.', 'were speaking': 'The teacher is singular. Use was.' },
    shapeCode: { subject: 'teacher', auxiliary: 'was', verbPhrase: 'speaking' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 2
  },
  {
    id: 'freeze-parallel-004', game: 'actionFreezeDetective',
    sentence: 'While I was cooking, my brother ___ the table.', clueText: 'While I was cooking',
    answer: 'was setting', options: ['set', 'was setting', 'were setting', 'sets'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Were there two actions at the same time?',
    meaningHint: 'Cooking and setting the table happened at the same time.',
    formHint: 'Use was/were + V-ing. Brother is singular, so use was.',
    explanation: 'While is the clue. Setting the table is a long action happening at the same time, so use was setting.',
    confusionTargets: ['set', 'were setting'],
    distractorRationale: { 'set': 'Setting the table takes time and happened together with cooking. Use was setting.', 'were setting': 'Brother is singular. Use was.' },
    shapeCode: { subject: 'brother', auxiliary: 'was', verbPhrase: 'setting' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 2
  },
  {
    id: 'freeze-parallel-005', game: 'actionFreezeDetective',
    sentence: 'I was reading while he ___ TV.', clueText: 'while',
    answer: 'was watching', options: ['watched', 'was watching', 'were watching', 'watches'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Were these actions happening together?',
    meaningHint: 'Reading and watching TV happened at the same time.',
    formHint: 'Use was/were + V-ing. He uses was.',
    explanation: 'While is the clue. Two long actions were happening together, so use was watching.',
    confusionTargets: ['watched', 'were watching'],
    distractorRationale: { 'watched': 'Watching TV is a long action. Use was watching.', 'were watching': 'Use was with He.' },
    shapeCode: { subject: 'he', auxiliary: 'was', verbPhrase: 'watching' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-006', game: 'actionFreezeDetective',
    sentence: 'While they were singing, we ___.', clueText: 'While they were singing',
    answer: 'were dancing', options: ['danced', 'was dancing', 'were dancing', 'dance'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'What happened at the same time as singing?',
    meaningHint: 'Dancing and singing happened together.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'While is the clue. Two actions happening together need the continuous form, so use were dancing.',
    confusionTargets: ['danced', 'was dancing'],
    distractorRationale: { 'danced': 'Dancing is a long action. Use were dancing.', 'was dancing': 'Use were with We.' },
    shapeCode: { subject: 'we', auxiliary: 'were', verbPhrase: 'dancing' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-007', game: 'actionFreezeDetective',
    sentence: 'She was painting while I ___ the piano.', clueText: 'while',
    answer: 'was playing', options: ['played', 'was playing', 'were playing', 'play'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Were these actions happening at the same time?',
    meaningHint: 'Painting and playing piano happened together.',
    formHint: 'Use was/were + V-ing. I uses was.',
    explanation: 'While is the clue. The long action was playing, so use was playing.',
    confusionTargets: ['played', 'were playing'],
    distractorRationale: { 'played': 'Playing is a long action. Use was playing.', 'were playing': 'Use was with I.' },
    shapeCode: { subject: 'I', auxiliary: 'was', verbPhrase: 'playing' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-008', game: 'actionFreezeDetective',
    sentence: 'While it was snowing outside, we ___ inside.', clueText: 'While it was snowing',
    answer: 'were staying', options: ['stayed', 'was staying', 'were staying', 'stay'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'What happened at the same time as the snow?',
    meaningHint: 'Snowing and staying inside happened together.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'While is the clue. The long action was staying, so use were staying.',
    confusionTargets: ['stayed', 'was staying'],
    distractorRationale: { 'stayed': 'Staying inside is a long action. Use were staying.', 'was staying': 'Use were with We.' },
    shapeCode: { subject: 'we', auxiliary: 'were', verbPhrase: 'staying' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 2
  },
  {
    id: 'freeze-parallel-009', game: 'actionFreezeDetective',
    sentence: 'My mom was driving while I ___ in the car.', clueText: 'while',
    answer: 'was sleeping', options: ['slept', 'was sleeping', 'were sleeping', 'sleep'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Were these long actions happening together?',
    meaningHint: 'Driving and sleeping happened at the same time.',
    formHint: 'Use was/were + V-ing. I uses was.',
    explanation: 'While is the clue. Sleeping is a long action, so use was sleeping.',
    confusionTargets: ['slept', 'were sleeping'],
    distractorRationale: { 'slept': 'Sleeping takes a long time. Use was sleeping.', 'were sleeping': 'Use was with I.' },
    shapeCode: { subject: 'I', auxiliary: 'was', verbPhrase: 'sleeping' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-010', game: 'actionFreezeDetective',
    sentence: 'While you were working, they ___.', clueText: 'While you were working',
    answer: 'were resting', options: ['rested', 'was resting', 'were resting', 'rest'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'What happened at the same time as working?',
    meaningHint: 'Working and resting happened together.',
    formHint: 'Use was/were + V-ing. They uses were.',
    explanation: 'While is the clue. Resting is a long action, so use were resting.',
    confusionTargets: ['rested', 'was resting'],
    distractorRationale: { 'rested': 'Resting takes a long time. Use were resting.', 'was resting': 'Use were with They.' },
    shapeCode: { subject: 'they', auxiliary: 'were', verbPhrase: 'resting' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-011', game: 'actionFreezeDetective',
    sentence: 'We ___ our homework while our parents were talking.', clueText: 'while our parents were talking',
    answer: 'were doing', options: ['did', 'was doing', 'were doing', 'do'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Were two long actions happening?',
    meaningHint: 'Doing homework and talking happened together.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'While is the clue. Doing homework is a long action, so use were doing.',
    confusionTargets: ['did', 'was doing'],
    distractorRationale: { 'did': 'Doing homework is a long action. Use were doing.', 'was doing': 'Use were with We.' },
    shapeCode: { subject: 'We', auxiliary: 'were', verbPhrase: 'doing' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-012', game: 'actionFreezeDetective',
    sentence: 'While the baby was sleeping, she ___ a book.', clueText: 'While the baby was sleeping',
    answer: 'was reading', options: ['read', 'was reading', 'were reading', 'reads'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'What happened at the same time as sleeping?',
    meaningHint: 'Sleeping and reading happened together.',
    formHint: 'Use was/were + V-ing. She uses was.',
    explanation: 'While is the clue. Reading is a long action, so use was reading.',
    confusionTargets: ['read', 'were reading'],
    distractorRationale: { 'read': 'Reading is a long action. Use was reading.', 'were reading': 'Use was with She.' },
    shapeCode: { subject: 'she', auxiliary: 'was', verbPhrase: 'reading' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-013', game: 'actionFreezeDetective',
    sentence: 'He was taking photos while we ___ around the city.', clueText: 'while',
    answer: 'were walking', options: ['walked', 'was walking', 'were walking', 'walk'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Were these actions happening together?',
    meaningHint: 'Taking photos and walking happened at the same time.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'While is the clue. Walking is a long action, so use were walking.',
    confusionTargets: ['walked', 'was walking'],
    distractorRationale: { 'walked': 'Walking is a long action. Use were walking.', 'was walking': 'Use were with We.' },
    shapeCode: { subject: 'we', auxiliary: 'were', verbPhrase: 'walking' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },
  {
    id: 'freeze-parallel-014', game: 'actionFreezeDetective',
    sentence: 'While she was cleaning, he ___ a cake.', clueText: 'While she was cleaning',
    answer: 'was baking', options: ['baked', 'was baking', 'were baking', 'bakes'],
    scenario: 'parallel_actions', scenarioLabel: 'Parallel Actions',
    clueQuestion: 'Did these long actions happen together?',
    meaningHint: 'Cleaning and baking happened at the same time.',
    formHint: 'Use was/were + V-ing. He uses was.',
    explanation: 'While is the clue. Baking is a long action, so use was baking.',
    confusionTargets: ['baked', 'were baking'],
    distractorRationale: { 'baked': 'Baking is a long action. Use was baking.', 'were baking': 'Use was with He.' },
    shapeCode: { subject: 'he', auxiliary: 'was', verbPhrase: 'baking' },
    tags: ['past_continuous', 'parallel_actions'], difficulty: 1
  },

  // EXACT PAST TIME (14 items)
  {
    id: 'freeze-exact-001', game: 'actionFreezeDetective',
    sentence: 'She ___ her bike at 5 PM yesterday.', clueText: 'at 5 PM yesterday',
    answer: 'was riding', options: ['rode', 'was riding', 'were riding', 'is riding'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was this action paused in the middle at exactly 5 PM?',
    meaningHint: 'An exact time in the past shows an action in progress.',
    formHint: 'Use was/were + V-ing. She uses was.',
    explanation: 'At 5 PM yesterday is the clue. This action was happening then, so use was riding.',
    confusionTargets: ['rode', 'were riding'],
    distractorRationale: { 'rode': 'The action was in the middle of happening at 5 PM. Use was riding.', 'were riding': 'Use was with She.' },
    shapeCode: { subject: 'She', auxiliary: 'was', verbPhrase: 'riding' },
    tags: ['past_continuous', 'exact_time'], difficulty: 2
  },
  {
    id: 'freeze-exact-002', game: 'actionFreezeDetective',
    sentence: 'You ___ at 8 o\'clock last night.', clueText: 'at 8 o\'clock',
    answer: 'were studying', options: ['studied', 'was studying', 'were studying', 'are studying'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was the action happening at that exact past time?',
    meaningHint: 'At 8 o\'clock last night means the action was in progress.',
    formHint: 'Use was/were + V-ing. You uses were.',
    explanation: 'At 8 o\'clock is the clue. This action was happening then, so use were studying.',
    confusionTargets: ['studied', 'was studying'],
    distractorRationale: { 'studied': 'The action was in progress at 8 o\'clock. Use were studying.', 'was studying': 'Use were with You.' },
    shapeCode: { subject: 'you', auxiliary: 'were', verbPhrase: 'studying' },
    tags: ['past_continuous', 'exact_time'], difficulty: 3
  },
  {
    id: 'freeze-exact-003', game: 'actionFreezeDetective',
    sentence: 'At midnight, everyone ___ deeply.', clueText: 'At midnight',
    answer: 'was sleeping', options: ['slept', 'was sleeping', 'were sleeping', 'sleeps'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was the action happening exactly at midnight?',
    meaningHint: 'At midnight indicates an action in progress.',
    formHint: 'Everyone takes a singular verb. Use was sleeping.',
    explanation: 'At midnight is the clue. This action was happening then, so use was sleeping.',
    confusionTargets: ['slept', 'were sleeping'],
    distractorRationale: { 'slept': 'The action was in progress at midnight. Use was sleeping.', 'were sleeping': 'Everyone is singular. Use was.' },
    shapeCode: { subject: 'everyone', auxiliary: 'was', verbPhrase: 'sleeping' },
    tags: ['past_continuous', 'exact_time', 'subject_agreement'], difficulty: 3
  },
  {
    id: 'freeze-exact-004', game: 'actionFreezeDetective',
    sentence: 'I ___ lunch at 1 PM yesterday.', clueText: 'at 1 PM yesterday',
    answer: 'was eating', options: ['ate', 'was eating', 'were eating', 'eat'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Were you in the middle of eating at 1 PM?',
    meaningHint: 'At 1 PM yesterday shows an action in progress.',
    formHint: 'Use was/were + V-ing. I uses was.',
    explanation: 'At 1 PM yesterday is the clue. You were in the middle of eating, so use was eating.',
    confusionTargets: ['ate', 'were eating'],
    distractorRationale: { 'ate': 'The action was in progress at exactly 1 PM. Use was eating.', 'were eating': 'Use was with I.' },
    shapeCode: { subject: 'I', auxiliary: 'was', verbPhrase: 'eating' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-005', game: 'actionFreezeDetective',
    sentence: 'They ___ football at 10 AM on Sunday.', clueText: 'at 10 AM on Sunday',
    answer: 'were playing', options: ['played', 'was playing', 'were playing', 'play'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Were they in the middle of playing at 10 AM?',
    meaningHint: 'At 10 AM shows an action in progress.',
    formHint: 'Use was/were + V-ing. They uses were.',
    explanation: 'At 10 AM on Sunday is the clue. The action was in progress, so use were playing.',
    confusionTargets: ['played', 'was playing'],
    distractorRationale: { 'played': 'The action was in progress at 10 AM. Use were playing.', 'was playing': 'Use were with They.' },
    shapeCode: { subject: 'They', auxiliary: 'were', verbPhrase: 'playing' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-006', game: 'actionFreezeDetective',
    sentence: 'We ___ to school at 7:30 this morning.', clueText: 'at 7:30 this morning',
    answer: 'were walking', options: ['walked', 'was walking', 'were walking', 'walk'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was the action happening exactly at 7:30?',
    meaningHint: 'At 7:30 this morning indicates an action in progress.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'At 7:30 this morning is the clue. You were in the middle of walking, so use were walking.',
    confusionTargets: ['walked', 'was walking'],
    distractorRationale: { 'walked': 'The action was in progress at 7:30. Use were walking.', 'was walking': 'Use were with We.' },
    shapeCode: { subject: 'We', auxiliary: 'were', verbPhrase: 'walking' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-007', game: 'actionFreezeDetective',
    sentence: 'He ___ his homework at 9 PM last night.', clueText: 'at 9 PM last night',
    answer: 'was doing', options: ['did', 'was doing', 'were doing', 'does'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was the action paused in the middle at 9 PM?',
    meaningHint: 'At 9 PM last night means the action was in progress.',
    formHint: 'Use was/were + V-ing. He uses was.',
    explanation: 'At 9 PM last night is the clue. The action was in progress, so use was doing.',
    confusionTargets: ['did', 'were doing'],
    distractorRationale: { 'did': 'The action was in progress at exactly 9 PM. Use was doing.', 'were doing': 'Use was with He.' },
    shapeCode: { subject: 'He', auxiliary: 'was', verbPhrase: 'doing' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-008', game: 'actionFreezeDetective',
    sentence: 'She ___ a picture at 4 o\'clock yesterday.', clueText: 'at 4 o\'clock yesterday',
    answer: 'was painting', options: ['painted', 'was painting', 'were painting', 'paints'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was she in the middle of painting at 4 o\'clock?',
    meaningHint: 'At 4 o\'clock yesterday shows an action in progress.',
    formHint: 'Use was/were + V-ing. She uses was.',
    explanation: 'At 4 o\'clock yesterday is the clue. She was in the middle of painting, so use was painting.',
    confusionTargets: ['painted', 'were painting'],
    distractorRationale: { 'painted': 'The action was in progress at 4 o\'clock. Use was painting.', 'were painting': 'Use was with She.' },
    shapeCode: { subject: 'She', auxiliary: 'was', verbPhrase: 'painting' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-009', game: 'actionFreezeDetective',
    sentence: 'At 6 PM, they ___ dinner.', clueText: 'At 6 PM',
    answer: 'were cooking', options: ['cooked', 'was cooking', 'were cooking', 'cook'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Were they in the middle of cooking at 6 PM?',
    meaningHint: 'At 6 PM shows an action in progress.',
    formHint: 'Use was/were + V-ing. They uses were.',
    explanation: 'At 6 PM is the clue. The action was in progress, so use were cooking.',
    confusionTargets: ['cooked', 'was cooking'],
    distractorRationale: { 'cooked': 'The action was in progress at 6 PM. Use were cooking.', 'was cooking': 'Use were with they.' },
    shapeCode: { subject: 'they', auxiliary: 'were', verbPhrase: 'cooking' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-010', game: 'actionFreezeDetective',
    sentence: 'I ___ to music at 11 PM last night.', clueText: 'at 11 PM last night',
    answer: 'was listening', options: ['listened', 'was listening', 'were listening', 'listen'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was the action happening exactly at 11 PM?',
    meaningHint: 'At 11 PM last night indicates an action in progress.',
    formHint: 'Use was/were + V-ing. I uses was.',
    explanation: 'At 11 PM last night is the clue. You were in the middle of listening, so use was listening.',
    confusionTargets: ['listened', 'were listening'],
    distractorRationale: { 'listened': 'The action was in progress at exactly 11 PM. Use was listening.', 'were listening': 'Use was with I.' },
    shapeCode: { subject: 'I', auxiliary: 'was', verbPhrase: 'listening' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-011', game: 'actionFreezeDetective',
    sentence: 'He ___ a shower at 7 AM this morning.', clueText: 'at 7 AM this morning',
    answer: 'was taking', options: ['took', 'was taking', 'were taking', 'takes'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was he in the middle of taking a shower at 7 AM?',
    meaningHint: 'At 7 AM shows an action in progress.',
    formHint: 'Use was/were + V-ing. He uses was.',
    explanation: 'At 7 AM this morning is the clue. The action was in progress, so use was taking.',
    confusionTargets: ['took', 'were taking'],
    distractorRationale: { 'took': 'The action was in progress at 7 AM. Use was taking.', 'were taking': 'Use was with He.' },
    shapeCode: { subject: 'He', auxiliary: 'was', verbPhrase: 'taking' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-012', game: 'actionFreezeDetective',
    sentence: 'We ___ TV at 8 PM yesterday.', clueText: 'at 8 PM yesterday',
    answer: 'were watching', options: ['watched', 'was watching', 'were watching', 'watch'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Were you in the middle of watching at 8 PM?',
    meaningHint: 'At 8 PM yesterday indicates an action in progress.',
    formHint: 'Use was/were + V-ing. We uses were.',
    explanation: 'At 8 PM yesterday is the clue. You were in the middle of watching, so use were watching.',
    confusionTargets: ['watched', 'was watching'],
    distractorRationale: { 'watched': 'The action was in progress at 8 PM. Use were watching.', 'was watching': 'Use were with We.' },
    shapeCode: { subject: 'We', auxiliary: 'were', verbPhrase: 'watching' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-013', game: 'actionFreezeDetective',
    sentence: 'She ___ her room at 10 AM on Saturday.', clueText: 'at 10 AM on Saturday',
    answer: 'was cleaning', options: ['cleaned', 'was cleaning', 'were cleaning', 'cleans'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Was the action happening exactly at 10 AM?',
    meaningHint: 'At 10 AM shows an action in progress.',
    formHint: 'Use was/were + V-ing. She uses was.',
    explanation: 'At 10 AM on Saturday is the clue. The action was in progress, so use was cleaning.',
    confusionTargets: ['cleaned', 'were cleaning'],
    distractorRationale: { 'cleaned': 'The action was in progress at exactly 10 AM. Use was cleaning.', 'were cleaning': 'Use was with She.' },
    shapeCode: { subject: 'She', auxiliary: 'was', verbPhrase: 'cleaning' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  },
  {
    id: 'freeze-exact-014', game: 'actionFreezeDetective',
    sentence: 'They ___ to music at noon yesterday.', clueText: 'at noon yesterday',
    answer: 'were listening', options: ['listened', 'was listening', 'were listening', 'listen'],
    scenario: 'exact_time', scenarioLabel: 'Exact Past Time',
    clueQuestion: 'Were they in the middle of listening at noon?',
    meaningHint: 'At noon yesterday indicates an action in progress.',
    formHint: 'Use was/were + V-ing. They uses were.',
    explanation: 'At noon yesterday is the clue. The action was in progress, so use were listening.',
    confusionTargets: ['listened', 'was listening'],
    distractorRationale: { 'listened': 'The action was in progress at noon. Use were listening.', 'was listening': 'Use were with They.' },
    shapeCode: { subject: 'They', auxiliary: 'were', verbPhrase: 'listening' },
    tags: ['past_continuous', 'exact_time'], difficulty: 1
  }
];
