export const futureForecastData = [
  // PLAN (8 items)
  {
    id: 'future-plan-001', game: 'futureForecastDetective',
    sentence: 'We bought tickets. We ___ watch a movie tonight.', clueText: 'bought tickets',
    answer: 'are going to', acceptedAnswers: ['are going to'], options: ['are going to', 'will', 'is going to', 'were going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Did they already decide or prepare?',
    meaningHint: 'The tickets show a plan before now.',
    formHint: 'Use are going to because the subject is We.',
    explanation: 'Bought tickets is the clue. This is a plan, so use are going to.',
    confusionTargets: ['will', 'is going to'],
    distractorRationale: { 'will': 'Will is for a decision now, not a prepared plan.', 'is going to': 'We needs are going to, not is going to.' },
    tags: ['future', 'plan', 'be_going_to', 'subject_agreement'], difficulty: 2
  },
  {
    id: 'future-plan-002', game: 'futureForecastDetective',
    sentence: 'She packed her bags because she ___ stay at her grandma\'s house.', clueText: 'packed her bags',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Is this a plan?',
    meaningHint: 'Packing bags shows it is already decided.',
    formHint: 'Use is going to for She.',
    explanation: 'Packed her bags is the clue. This is a plan, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Packing bags means it is a plan, not a quick decision.', 'are going to': 'She uses is going to.' },
    tags: ['future', 'plan', 'going_to'], difficulty: 2
  },
  {
    id: 'future-plan-003', game: 'futureForecastDetective',
    sentence: 'I booked the hotel. I ___ visit London next month.', clueText: 'booked the hotel',
    answer: 'am going to', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Did you prepare already?',
    meaningHint: 'Booking the hotel makes it a firm plan.',
    formHint: 'Use am going to for I.',
    explanation: 'Booked the hotel is the clue. This is a plan, so use am going to.',
    confusionTargets: ['will', 'is going to'],
    distractorRationale: { 'will': 'Will is for a sudden decision. You booked it already, so it is a plan.', 'is going to': 'I uses am going to.' },
    tags: ['future', 'plan', 'going_to'], difficulty: 2
  },
  {
    id: 'future-plan-004', game: 'futureForecastDetective',
    sentence: 'My dad called the restaurant. We ___ eat out tonight.', clueText: 'called the restaurant',
    answer: 'are going to', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Is this planned?',
    meaningHint: 'Calling the restaurant shows preparation.',
    formHint: 'Use are going to for We.',
    explanation: 'Called the restaurant is the clue. This is a plan, so use are going to.',
    confusionTargets: ['will', 'is going to'],
    distractorRationale: { 'will': 'Will is for a quick decision. Calling ahead makes it a plan.', 'is going to': 'We uses are going to.' },
    tags: ['future', 'plan', 'going_to'], difficulty: 2
  },
  {
    id: 'future-plan-005', game: 'futureForecastDetective',
    sentence: 'He bought flour and eggs. He ___ bake a cake.', clueText: 'bought flour and eggs',
    answer: 'is going to', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Did he prepare for this?',
    meaningHint: 'Buying ingredients shows an intention.',
    formHint: 'Use is going to for He.',
    explanation: 'Bought flour and eggs is the clue. This is a plan, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for instant decisions. He prepared, so use is going to.', 'are going to': 'He uses is going to.' },
    tags: ['future', 'plan', 'going_to'], difficulty: 2
  },
  {
    id: 'future-plan-006', game: 'futureForecastDetective',
    sentence: 'They have a map. They ___ explore the city.', clueText: 'have a map',
    answer: 'are going to', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Is this a plan?',
    meaningHint: 'Having a map means they intend to explore.',
    formHint: 'Use are going to for They.',
    explanation: 'Have a map is the clue. This is a plan, so use are going to.',
    confusionTargets: ['will', 'is going to'],
    distractorRationale: { 'will': 'Having a map shows preparation. Use are going to.', 'is going to': 'They uses are going to.' },
    tags: ['future', 'plan', 'going_to'], difficulty: 1
  },
  {
    id: 'future-plan-007', game: 'futureForecastDetective',
    sentence: 'I put on my sports shoes. I ___ run in the park.', clueText: 'put on my sports shoes',
    answer: 'am going to', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Did you prepare to run?',
    meaningHint: 'Putting on shoes shows a clear intention.',
    formHint: 'Use am going to for I.',
    explanation: 'Put on my sports shoes is the clue. This is a plan, so use am going to.',
    confusionTargets: ['will', 'is going to'],
    distractorRationale: { 'will': 'Will is for sudden decisions. This is an intention.', 'is going to': 'I uses am going to.' },
    tags: ['future', 'plan', 'going_to'], difficulty: 1
  },
  {
    id: 'future-plan-008', game: 'futureForecastDetective',
    sentence: 'We invited everyone. We ___ have a big party.', clueText: 'invited everyone',
    answer: 'are going to', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'plan', scenarioLabel: 'Plan',
    clueQuestion: 'Is the party planned?',
    meaningHint: 'Inviting everyone shows the party is planned.',
    formHint: 'Use are going to for We.',
    explanation: 'Invited everyone is the clue. This is a plan, so use are going to.',
    confusionTargets: ['will', 'is going to'],
    distractorRationale: { 'will': 'Will is for quick decisions. Inviting people makes it a plan.', 'is going to': 'We uses are going to.' },
    tags: ['future', 'plan', 'going_to'], difficulty: 1
  },

  // VISIBLE EVIDENCE (8 items)
  {
    id: 'future-evidence-001', game: 'futureForecastDetective',
    sentence: 'Look at those dark clouds! It ___ rain.', clueText: 'dark clouds',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'Can you see evidence right now?',
    meaningHint: 'Dark clouds are visible evidence.',
    formHint: 'Use is going to for It.',
    explanation: 'Dark clouds is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for an opinion. Dark clouds are real evidence, so use is going to.', 'are going to': 'It uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 1
  },
  {
    id: 'future-evidence-002', game: 'futureForecastDetective',
    sentence: 'Watch out! That glass ___ fall off the table!', clueText: 'Watch out',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'Is there immediate danger you can see?',
    meaningHint: 'Watch out means there is immediate visible danger.',
    formHint: 'Use is going to for That glass (It).',
    explanation: 'Watch out is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for a guess. This is an immediate danger you can see, so use is going to.', 'are going to': 'That glass uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 2
  },
  {
    id: 'future-evidence-003', game: 'futureForecastDetective',
    sentence: 'The car is driving too fast towards the tree. It ___ crash!', clueText: 'too fast towards the tree',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'Can you see what will happen?',
    meaningHint: 'Driving too fast towards a tree is clear evidence.',
    formHint: 'Use is going to for It.',
    explanation: 'Too fast towards the tree is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for a guess. You can see it happening, so use is going to.', 'are going to': 'It uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 1
  },
  {
    id: 'future-evidence-004', game: 'futureForecastDetective',
    sentence: 'Look at his pale face. He ___ be sick.', clueText: 'pale face',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'What can you see?',
    meaningHint: 'A pale face is evidence he will be sick.',
    formHint: 'Use is going to for He.',
    explanation: 'Pale face is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for a guess. A pale face is evidence, so use is going to.', 'are going to': 'He uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 2
  },
  {
    id: 'future-evidence-005', game: 'futureForecastDetective',
    sentence: 'There is a huge hole in the road ahead. The bike ___ fall in.', clueText: 'huge hole in the road',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'Is there clear evidence of danger?',
    meaningHint: 'The hole is clear evidence.',
    formHint: 'Use is going to for The bike.',
    explanation: 'Huge hole in the road is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for an opinion. The hole is real evidence, so use is going to.', 'are going to': 'The bike uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 1
  },
  {
    id: 'future-evidence-006', game: 'futureForecastDetective',
    sentence: 'The runner is 100 meters ahead of everyone. He ___ win the race.', clueText: '100 meters ahead',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'Can you see who will win?',
    meaningHint: 'Being 100 meters ahead is clear evidence.',
    formHint: 'Use is going to for He.',
    explanation: '100 meters ahead is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for a guess. Being far ahead is evidence, so use is going to.', 'are going to': 'He uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 1
  },
  {
    id: 'future-evidence-007', game: 'futureForecastDetective',
    sentence: 'Look at that tall stack of books wobbling. It ___ fall over!', clueText: 'wobbling',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'Is there evidence right now?',
    meaningHint: 'Wobbling is visible evidence it will fall.',
    formHint: 'Use is going to for It.',
    explanation: 'Wobbling is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for an opinion. Wobbling is real evidence, so use is going to.', 'are going to': 'It uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 2
  },
  {
    id: 'future-evidence-008', game: 'futureForecastDetective',
    sentence: 'The sky is completely blue and sunny. It ___ be a hot day.', clueText: 'blue and sunny',
    answer: 'is going to', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'visible_evidence', scenarioLabel: 'Visible Evidence',
    clueQuestion: 'Can you see evidence in the sky?',
    meaningHint: 'A blue, sunny sky is evidence of a hot day.',
    formHint: 'Use is going to for It.',
    explanation: 'Blue and sunny is the clue. This is visible evidence, so use is going to.',
    confusionTargets: ['will', 'are going to'],
    distractorRationale: { 'will': 'Will is for a guess. The blue sky is evidence, so use is going to.', 'are going to': 'It uses is going to.' },
    tags: ['future', 'evidence', 'going_to'], difficulty: 1
  },

  // QUICK DECISION (8 items)
  {
    id: 'future-decision-001', game: 'futureForecastDetective',
    sentence: 'The phone is ringing. I ___ answer it.', clueText: 'is ringing',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Did you decide right now?',
    meaningHint: 'You decided to answer it right now.',
    formHint: 'Use will for a quick decision.',
    explanation: 'Is ringing is the clue. You decide now, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a plan. You didn\'t plan for the phone to ring, you decided now. Use will.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 1
  },
  {
    id: 'future-decision-002', game: 'futureForecastDetective',
    sentence: 'I am thirsty. I ___ get a glass of water.', clueText: 'am thirsty',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Did you decide just now?',
    meaningHint: 'Being thirsty makes you decide right now.',
    formHint: 'Use will for an instant decision.',
    explanation: 'Am thirsty is the clue. You decide now, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a prepared plan. This is a sudden decision. Use will.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 1
  },
  {
    id: 'future-decision-003', game: 'futureForecastDetective',
    sentence: 'It is very cold in here. I ___ close the window.', clueText: 'is very cold',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Did the speaker decide right now?',
    meaningHint: 'Feeling cold makes you decide to close it now.',
    formHint: 'Use will for a quick decision.',
    explanation: 'Is very cold is the clue. This is a quick decision, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a plan. You decide to close it now, so use will.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 1
  },
  {
    id: 'future-decision-004', game: 'futureForecastDetective',
    sentence: 'Someone is at the door. I ___ see who it is.', clueText: 'Someone is at the door',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Did the speaker decide right now?',
    meaningHint: 'You didn\'t plan it, you decided just now.',
    formHint: 'Use will for an instant decision.',
    explanation: 'Someone is at the door is the clue. You decide now, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a plan. You didn\'t plan for someone to come, you decided now.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 2
  },
  {
    id: 'future-decision-005', game: 'futureForecastDetective',
    sentence: 'I forgot my pen. I ___ borrow one from Tom.', clueText: 'forgot my pen',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Is this a plan or a quick decision?',
    meaningHint: 'Forgetting a pen means you must decide now.',
    formHint: 'Use will for a sudden decision.',
    explanation: 'Forgot my pen is the clue. You decide now, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. You didn\'t plan to forget your pen. Use will.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 2
  },
  {
    id: 'future-decision-006', game: 'futureForecastDetective',
    sentence: 'That shirt looks nice. I think I ___ buy it.', clueText: 'looks nice',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Did you decide right now?',
    meaningHint: 'Seeing the shirt makes you decide now.',
    formHint: 'Use will for a quick decision.',
    explanation: 'Looks nice is the clue. You decide now, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a plan you made before. This is a quick decision, so use will.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 1
  },
  {
    id: 'future-decision-007', game: 'futureForecastDetective',
    sentence: 'There is no milk left. I ___ go to the shop and get some.', clueText: 'no milk left',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Did the speaker decide right now?',
    meaningHint: 'Seeing no milk makes you decide now.',
    formHint: 'Use will for a sudden decision.',
    explanation: 'No milk left is the clue. You decide now, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. You didn\'t know there was no milk. It is a quick decision.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 2
  },
  {
    id: 'future-decision-008', game: 'futureForecastDetective',
    sentence: 'My bag is broken. I ___ buy a new one today.', clueText: 'is broken',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'quick_decision', scenarioLabel: 'Quick Decision',
    clueQuestion: 'Did you decide just now?',
    meaningHint: 'Finding the bag is broken makes you decide now.',
    formHint: 'Use will for an instant decision.',
    explanation: 'Is broken is the clue. You decide now, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a plan. You didn\'t plan for it to break. Use will.' },
    tags: ['future', 'quick_decision', 'will'], difficulty: 1
  },

  // PROMISE (8 items)
  {
    id: 'future-promise-001', game: 'futureForecastDetective',
    sentence: 'I promise I ___ help you with your homework tonight.', clueText: 'promise',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is the speaker promising?',
    meaningHint: 'For a promise, use will.',
    formHint: 'Use will for promises.',
    explanation: 'Promise is the clue. This is a promise, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for promises.' },
    tags: ['future', 'promise', 'will'], difficulty: 1
  },
  {
    id: 'future-promise-002', game: 'futureForecastDetective',
    sentence: 'Don\'t worry, I ___ keep your secret.', clueText: 'Don\'t worry',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is the speaker promising?',
    meaningHint: 'Saying "Don\'t worry" is like making a promise.',
    formHint: 'Use will for promises.',
    explanation: 'Don\'t worry is the clue. This is a promise, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for a promise.' },
    tags: ['future', 'promise', 'will'], difficulty: 2
  },
  {
    id: 'future-promise-003', game: 'futureForecastDetective',
    sentence: 'I swear I ___ tell anyone what happened.', clueText: 'swear',
    answer: 'will not', acceptedAnswers: ['will not', 'won\'t'], options: ['will not', 'am not going to', 'is not going to', 'are not going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is this a strong promise?',
    meaningHint: 'Swearing is making a strong promise.',
    formHint: 'Use will (or will not) for promises.',
    explanation: 'Swear is the clue. This is a promise, so use will not.',
    confusionTargets: ['am not going to'],
    distractorRationale: { 'am not going to': 'Going to is for plans. Use will not for a promise.' },
    tags: ['future', 'promise', 'will', 'negative'], difficulty: 2
  },
  {
    id: 'future-promise-004', game: 'futureForecastDetective',
    sentence: 'I promise we ___ be careful with the ball.', clueText: 'promise',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is the speaker making a promise?',
    meaningHint: 'For a promise, use will.',
    formHint: 'Use will for promises.',
    explanation: 'Promise is the clue. This is a promise, so use will.',
    confusionTargets: ['are going to'],
    distractorRationale: { 'are going to': 'Going to is for plans. Use will for a promise.' },
    tags: ['future', 'promise', 'will'], difficulty: 1
  },
  {
    id: 'future-promise-005', game: 'futureForecastDetective',
    sentence: 'Trust me, I ___ pay you back tomorrow.', clueText: 'Trust me',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is the speaker promising?',
    meaningHint: 'Saying "Trust me" is a promise.',
    formHint: 'Use will for promises.',
    explanation: 'Trust me is the clue. This is a promise, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for promises.' },
    tags: ['future', 'promise', 'will'], difficulty: 1
  },
  {
    id: 'future-promise-006', game: 'futureForecastDetective',
    sentence: 'I promise she ___ come to your party.', clueText: 'promise',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is this a promise?',
    meaningHint: 'For a promise, use will.',
    formHint: 'Use will for promises.',
    explanation: 'Promise is the clue. This is a promise, so use will.',
    confusionTargets: ['is going to'],
    distractorRationale: { 'is going to': 'Going to is for plans. Use will for promises.' },
    tags: ['future', 'promise', 'will'], difficulty: 1
  },
  {
    id: 'future-promise-007', game: 'futureForecastDetective',
    sentence: 'We promise we ___ finish the project on time.', clueText: 'promise',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is the speaker promising?',
    meaningHint: 'For a promise, use will.',
    formHint: 'Use will for promises.',
    explanation: 'Promise is the clue. This is a promise, so use will.',
    confusionTargets: ['are going to'],
    distractorRationale: { 'are going to': 'Going to is for plans. Use will for promises.' },
    tags: ['future', 'promise', 'will'], difficulty: 1
  },
  {
    id: 'future-promise-008', game: 'futureForecastDetective',
    sentence: 'I promise I ___ forget your birthday again.', clueText: 'promise',
    answer: 'will not', acceptedAnswers: ['will not', 'won\'t'], options: ['will not', 'am not going to', 'is not going to', 'are not going to'],
    scenario: 'promise', scenarioLabel: 'Promise',
    clueQuestion: 'Is the speaker making a promise?',
    meaningHint: 'For a promise, use will (or will not).',
    formHint: 'Use will not for a negative promise.',
    explanation: 'Promise is the clue. This is a negative promise, so use will not.',
    confusionTargets: ['am not going to'],
    distractorRationale: { 'am not going to': 'Going to is for plans. Use will not for promises.' },
    tags: ['future', 'promise', 'will', 'negative'], difficulty: 2
  },

  // OFFER (8 items)
  {
    id: 'future-offer-001', game: 'futureForecastDetective',
    sentence: 'Oh, you dropped your pen. I ___ pick it up for you.', clueText: 'pick it up for you',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker offering to help?',
    meaningHint: 'Offering to help someone means you decide to do it now.',
    formHint: 'Use will for an offer to help.',
    explanation: 'Pick it up for you is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. You didn\'t plan to pick it up, you offered to help now. Use will.' },
    tags: ['future', 'offer', 'will'], difficulty: 2
  },
  {
    id: 'future-offer-002', game: 'futureForecastDetective',
    sentence: 'That box looks heavy. I ___ help you carry it.', clueText: 'help you',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker offering to help?',
    meaningHint: 'Offering to help someone uses will.',
    formHint: 'Use will for an offer.',
    explanation: 'Help you is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for an offer to help.' },
    tags: ['future', 'offer', 'will'], difficulty: 1
  },
  {
    id: 'future-offer-003', game: 'futureForecastDetective',
    sentence: 'You seem tired. I ___ wash the dishes tonight.', clueText: 'wash the dishes',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker offering to do a chore?',
    meaningHint: 'Offering to wash dishes is a helpful offer.',
    formHint: 'Use will for an offer.',
    explanation: 'Wash the dishes is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a plan. Use will for a spontaneous offer to help.' },
    tags: ['future', 'offer', 'will'], difficulty: 2
  },
  {
    id: 'future-offer-004', game: 'futureForecastDetective',
    sentence: 'I see you are busy. I ___ answer the door.', clueText: 'answer the door',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker offering to help?',
    meaningHint: 'Offering to answer the door uses will.',
    formHint: 'Use will for an offer.',
    explanation: 'Answer the door is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for a plan. Use will for an offer.' },
    tags: ['future', 'offer', 'will'], difficulty: 1
  },
  {
    id: 'future-offer-005', game: 'futureForecastDetective',
    sentence: 'If you are cold, I ___ lend you my jacket.', clueText: 'lend you',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker offering something?',
    meaningHint: 'Offering to lend a jacket is a helpful offer.',
    formHint: 'Use will for an offer.',
    explanation: 'Lend you is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for an offer.' },
    tags: ['future', 'offer', 'will'], difficulty: 1
  },
  {
    id: 'future-offer-006', game: 'futureForecastDetective',
    sentence: 'Don\'t worry about the cleaning. I ___ do it.', clueText: 'do it',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker volunteering to do it?',
    meaningHint: 'Volunteering or offering uses will.',
    formHint: 'Use will for an offer.',
    explanation: 'Do it is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for an offer.' },
    tags: ['future', 'offer', 'will'], difficulty: 1
  },
  {
    id: 'future-offer-007', game: 'futureForecastDetective',
    sentence: 'You look lost. I ___ show you the way on the map.', clueText: 'show you',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker offering help?',
    meaningHint: 'Offering to show the way uses will.',
    formHint: 'Use will for an offer.',
    explanation: 'Show you is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for an offer.' },
    tags: ['future', 'offer', 'will'], difficulty: 2
  },
  {
    id: 'future-offer-008', game: 'futureForecastDetective',
    sentence: 'I have some free time. I ___ help you study.', clueText: 'help you',
    answer: 'will', options: ['will', 'am going to', 'is going to', 'are going to'],
    scenario: 'offer', scenarioLabel: 'Offer',
    clueQuestion: 'Is the speaker offering to help?',
    meaningHint: 'Offering to help study uses will.',
    formHint: 'Use will for an offer.',
    explanation: 'Help you is the clue. This is an offer, so use will.',
    confusionTargets: ['am going to'],
    distractorRationale: { 'am going to': 'Going to is for plans. Use will for an offer.' },
    tags: ['future', 'offer', 'will'], difficulty: 1
  },

  // OPINION (8 items)
  {
    id: 'future-opinion-001', game: 'futureForecastDetective',
    sentence: 'I think that team ___ win the match today.', clueText: 'think',
    answer: 'will', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is the speaker making a guess or opinion?',
    meaningHint: '"I think" shows it is an opinion or guess.',
    formHint: 'Use will for an opinion.',
    explanation: 'Think is the clue. This is an opinion, so use will.',
    confusionTargets: ['is going to'],
    distractorRationale: { 'is going to': 'Going to is for real evidence. "I think" is just an opinion, so use will.' },
    tags: ['future', 'opinion', 'will'], difficulty: 1
  },
  {
    id: 'future-opinion-002', game: 'futureForecastDetective',
    sentence: 'I believe robots ___ do all our housework in the future.', clueText: 'believe',
    answer: 'will', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is this what the speaker thinks will happen?',
    meaningHint: '"I believe" shows it is an opinion.',
    formHint: 'Use will for opinions and predictions.',
    explanation: 'Believe is the clue. This is an opinion, so use will.',
    confusionTargets: ['are going to'],
    distractorRationale: { 'are going to': 'Going to is for evidence. "I believe" is an opinion, so use will.' },
    tags: ['future', 'opinion', 'will'], difficulty: 1
  },
  {
    id: 'future-opinion-003', game: 'futureForecastDetective',
    sentence: 'She will probably ___ pass the exam easily.', clueText: 'probably',
    answer: 'will', acceptedAnswers: ['will'], options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is the speaker guessing what will happen?',
    meaningHint: '"Probably" shows it is a guess or opinion.',
    formHint: 'Use will with words like probably.',
    explanation: 'Probably is the clue. This is an opinion, so use will.',
    confusionTargets: ['is going to'],
    distractorRationale: { 'is going to': 'Going to is for evidence. "Probably" is a guess, so use will.' },
    tags: ['future', 'opinion', 'will'], difficulty: 2
  },
  {
    id: 'future-opinion-004', game: 'futureForecastDetective',
    sentence: 'I hope it ___ be sunny tomorrow.', clueText: 'hope',
    answer: 'will', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is the speaker expressing a wish or opinion?',
    meaningHint: '"I hope" shows an opinion or wish.',
    formHint: 'Use will for hopes and opinions.',
    explanation: 'Hope is the clue. This is an opinion, so use will.',
    confusionTargets: ['is going to'],
    distractorRationale: { 'is going to': 'Going to is for evidence. "I hope" is an opinion, so use will.' },
    tags: ['future', 'opinion', 'will'], difficulty: 1
  },
  {
    id: 'future-opinion-005', game: 'futureForecastDetective',
    sentence: 'I think you ___ enjoy this movie.', clueText: 'think',
    answer: 'will', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is the speaker giving their opinion?',
    meaningHint: '"I think" shows it is an opinion.',
    formHint: 'Use will for opinions.',
    explanation: 'Think is the clue. This is an opinion, so use will.',
    confusionTargets: ['are going to'],
    distractorRationale: { 'are going to': 'Going to is for plans. "I think" is an opinion, so use will.' },
    tags: ['future', 'opinion', 'will'], difficulty: 1
  },
  {
    id: 'future-opinion-006', game: 'futureForecastDetective',
    sentence: 'I am sure they ___ win the game.', clueText: 'am sure',
    answer: 'will', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is the speaker giving their strong opinion?',
    meaningHint: '"I am sure" shows a strong opinion or belief.',
    formHint: 'Use will for beliefs and opinions.',
    explanation: 'Am sure is the clue. This is an opinion, so use will.',
    confusionTargets: ['are going to'],
    distractorRationale: { 'are going to': 'Going to is for evidence. "I am sure" is an opinion, so use will.' },
    tags: ['future', 'opinion', 'will'], difficulty: 2
  },
  {
    id: 'future-opinion-007', game: 'futureForecastDetective',
    sentence: 'Maybe he ___ arrive late.', clueText: 'Maybe',
    answer: 'will', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is the speaker guessing?',
    meaningHint: '"Maybe" shows it is a guess or opinion.',
    formHint: 'Use will for a guess.',
    explanation: 'Maybe is the clue. This is an opinion, so use will.',
    confusionTargets: ['is going to'],
    distractorRationale: { 'is going to': 'Going to is for evidence. "Maybe" is an opinion, so use will.' },
    tags: ['future', 'opinion', 'will'], difficulty: 1
  },
  {
    id: 'future-opinion-008', game: 'futureForecastDetective',
    sentence: 'I don\'t think it ___ snow tonight.', clueText: 'don\'t think',
    answer: 'will', options: ['will', 'is going to', 'am going to', 'are going to'],
    scenario: 'opinion', scenarioLabel: 'Opinion',
    clueQuestion: 'Is the speaker giving their opinion?',
    meaningHint: '"Don\'t think" shows a negative opinion.',
    formHint: 'Use will for opinions.',
    explanation: 'Don\'t think is the clue. This is an opinion, so use will.',
    confusionTargets: ['is going to'],
    distractorRationale: { 'is going to': 'Going to is for evidence. "Don\'t think" is an opinion, so use will.' },
    tags: ['future', 'opinion', 'will', 'negative'], difficulty: 1
  }
];
