export const modalData = [
  // ABILITY NOW (8 items)
  {
    id: 'modal-ability-001', game: 'modalDetective',
    sentence: 'I ___ play the piano.', clueText: 'play the piano',
    answer: 'can', acceptedAnswers: ['can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Is this a skill someone has now?',
    meaningHint: 'Playing the piano is a present skill.',
    formHint: 'Use can for a skill you have now.',
    explanation: 'Play the piano is the clue. This is an ability now, so use can.',
    confusionTargets: ['could'],
    distractorRationale: { 'could': 'Could is for a past skill, not a present one.', 'may': 'May is for permission, not a skill.', 'might': 'Might is for maybe, not a skill.' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 1
  },
  {
    id: 'modal-ability-002', game: 'modalDetective',
    sentence: 'My brother ___ speak English and Vietnamese.', clueText: 'speak English and Vietnamese',
    answer: 'can', options: ['can', 'could', 'may', 'might'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Is this a skill someone has now?',
    meaningHint: 'Speaking languages is an ability now.',
    formHint: 'Use can for a current skill.',
    explanation: 'Speak languages is the clue. This is an ability now, so use can.',
    confusionTargets: ['could'],
    distractorRationale: { 'could': 'Could is for a past skill.', 'may': 'May is for permission or maybe.' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 1
  },
  {
    id: 'modal-ability-003', game: 'modalDetective',
    sentence: 'This bag is heavy, but I ___ carry it.', clueText: 'carry it',
    answer: 'can', options: ['can', 'could', 'may', 'might'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Can the speaker do it now?',
    meaningHint: 'Carrying it is something they are able to do now.',
    formHint: 'Use can for present ability.',
    explanation: 'Carry it is the clue. This is an ability now, so use can.',
    confusionTargets: ['could'],
    distractorRationale: { 'could': 'Could is for the past.', 'might': 'The speaker is sure they can do it.' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 1
  },
  {
    id: 'modal-ability-004', game: 'modalDetective',
    sentence: 'She practices every day, so she ___ dance very well.', clueText: 'dance very well',
    answer: 'can', options: ['can', 'could', 'may', 'might'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Is this a skill she has now?',
    meaningHint: 'Dancing well is a skill she has today.',
    formHint: 'Use can for a skill now.',
    explanation: 'Dance very well is the clue. This is an ability now, so use can.',
    confusionTargets: ['could'],
    distractorRationale: { 'could': 'Could is for a past skill, but she practices every day (now).' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 2
  },
  {
    id: 'modal-ability-005', game: 'modalDetective',
    sentence: 'Birds ___ fly high in the sky.', clueText: 'fly high',
    answer: 'can', options: ['can', 'could', 'may', 'might'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Is this a skill birds have?',
    meaningHint: 'Flying is a natural ability.',
    formHint: 'Use can for a skill or ability.',
    explanation: 'Fly high is the clue. This is an ability, so use can.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'May is for permission. Birds don\'t need permission to fly.', 'could': 'Could is for past ability.' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 1
  },
  {
    id: 'modal-ability-006', game: 'modalDetective',
    sentence: 'I ___ swim across the pool.', clueText: 'swim',
    answer: 'can', options: ['can', 'could', 'may', 'might'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Is this a present skill?',
    meaningHint: 'Swimming is an ability now.',
    formHint: 'Use can for current ability.',
    explanation: 'Swim is the clue. This is an ability now, so use can.',
    confusionTargets: ['could'],
    distractorRationale: { 'could': 'Could is for the past, but there is no past time clue here.' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 1
  },
  {
    id: 'modal-ability-007', game: 'modalDetective',
    sentence: 'My dad ___ fix computers.', clueText: 'fix computers',
    answer: 'can', options: ['can', 'could', 'may', 'might'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Is this a skill he has?',
    meaningHint: 'Fixing computers is a skill.',
    formHint: 'Use can for ability.',
    explanation: 'Fix computers is the clue. This is an ability now, so use can.',
    confusionTargets: ['could'],
    distractorRationale: { 'could': 'There is no past clue, so use can.' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 1
  },
  {
    id: 'modal-ability-008', game: 'modalDetective',
    sentence: 'We ___ solve this math problem easily.', clueText: 'solve this math problem',
    answer: 'can', options: ['can', 'could', 'may', 'must'],
    scenario: 'ability_now', scenarioLabel: 'Ability Now',
    clueQuestion: 'Are they able to do it?',
    meaningHint: 'Solving it easily shows they have the ability.',
    formHint: 'Use can for ability.',
    explanation: 'Solve this math problem is the clue. This is an ability, so use can.',
    confusionTargets: ['must'],
    distractorRationale: { 'must': 'Must is for rules, not ability.', 'could': 'Could is for the past.' },
    tags: ['modal', 'can', 'ability_now'], difficulty: 2
  },

  // PAST ABILITY (8 items)
  {
    id: 'modal-pastability-001', game: 'modalDetective',
    sentence: 'When I was five, I ___ ride a bike.', clueText: 'When I was five',
    answer: 'could', options: ['can', 'could', 'may', 'might'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'When I was five means before now.',
    formHint: 'Use could for past ability.',
    explanation: 'When I was five is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability now, not when I was five.' },
    tags: ['modal', 'could', 'past_ability'], difficulty: 1
  },
  {
    id: 'modal-pastability-002', game: 'modalDetective',
    sentence: 'My grandfather ___ run fast when he was young.', clueText: 'when he was young',
    answer: 'could', options: ['can', 'could', 'may', 'might'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'When he was young means before.',
    formHint: 'Use could for a past skill.',
    explanation: 'When he was young is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for now. He is old now, so use could for when he was young.' },
    tags: ['modal', 'could', 'past_ability'], difficulty: 1
  },
  {
    id: 'modal-pastability-003', game: 'modalDetective',
    sentence: 'Before she moved here, she ___ not speak Vietnamese.', clueText: 'Before she moved here',
    answer: 'could', options: ['can', 'could', 'may', 'might'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this about ability before now?',
    meaningHint: 'Before she moved here is a past clue.',
    formHint: 'Use could (or could not) for the past.',
    explanation: 'Before she moved here is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Use could because it happened before she moved.' },
    tags: ['modal', 'could', 'past_ability', 'negative'], difficulty: 2
  },
  {
    id: 'modal-pastability-004', game: 'modalDetective',
    sentence: 'At age six, he ___ read simple books.', clueText: 'At age six',
    answer: 'could', options: ['can', 'could', 'may', 'might'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'At age six happened before.',
    formHint: 'Use could for past ability.',
    explanation: 'At age six is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'At age six is in the past, so use could.' },
    tags: ['modal', 'could', 'past_ability'], difficulty: 2
  },
  {
    id: 'modal-pastability-005', game: 'modalDetective',
    sentence: 'Two years ago, I ___ swim very fast.', clueText: 'Two years ago',
    answer: 'could', options: ['can', 'could', 'may', 'might'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'Two years ago is a past time.',
    formHint: 'Use could for a past skill.',
    explanation: 'Two years ago is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Two years ago is the past. Use could.' },
    tags: ['modal', 'could', 'past_ability'], difficulty: 1
  },
  {
    id: 'modal-pastability-006', game: 'modalDetective',
    sentence: 'Last summer, we ___ climb that tall tree.', clueText: 'Last summer',
    answer: 'could', options: ['can', 'could', 'may', 'might'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'Last summer is a past time marker.',
    formHint: 'Use could for past ability.',
    explanation: 'Last summer is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Last summer is the past. Use could.' },
    tags: ['modal', 'could', 'past_ability'], difficulty: 1
  },
  {
    id: 'modal-pastability-007', game: 'modalDetective',
    sentence: 'She ___ dance for hours when she was a teenager.', clueText: 'when she was a teenager',
    answer: 'could', options: ['can', 'could', 'may', 'might'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this a past skill?',
    meaningHint: 'When she was a teenager is a past time.',
    formHint: 'Use could for past ability.',
    explanation: 'When she was a teenager is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'When she was a teenager is the past. Use could.' },
    tags: ['modal', 'could', 'past_ability'], difficulty: 1
  },
  {
    id: 'modal-pastability-008', game: 'modalDetective',
    sentence: 'Before he broke his arm, he ___ carry heavy boxes.', clueText: 'Before he broke his arm',
    answer: 'could', options: ['can', 'could', 'may', 'must'],
    scenario: 'past_ability', scenarioLabel: 'Past Ability',
    clueQuestion: 'Is this about ability before?',
    meaningHint: 'Before he broke his arm shows it is a past ability.',
    formHint: 'Use could for past ability.',
    explanation: 'Before he broke his arm is the clue. This is a past ability, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'This happened before, so use could.', 'must': 'Must is for rules.' },
    tags: ['modal', 'could', 'past_ability'], difficulty: 2
  },

  // PERMISSION (8 items)
  {
    id: 'modal-permission-001', game: 'modalDetective',
    sentence: '___ I open the window, please?', clueText: 'please',
    answer: 'may', acceptedAnswers: ['can', 'may'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Is someone asking if it is allowed?',
    meaningHint: 'They are asking for permission to open the window.',
    formHint: 'Use may or can to ask permission.',
    explanation: 'Please is the clue. This is permission, so use may (or can).',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might is for maybe. You do not use might to ask permission to open a window.' },
    tags: ['modal', 'may', 'permission'], difficulty: 1
  },
  {
    id: 'modal-permission-002', game: 'modalDetective',
    sentence: '___ I come in, teacher?', clueText: 'teacher',
    answer: 'may', acceptedAnswers: ['may', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Is someone asking permission politely?',
    meaningHint: 'Asking a teacher requires formal permission.',
    formHint: 'Use may for polite permission.',
    explanation: 'Teacher is the clue. This is polite permission, so use may.',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might is for maybe, not for asking a teacher permission.' },
    tags: ['modal', 'may', 'permission', 'polite'], difficulty: 1
  },
  {
    id: 'modal-permission-003', game: 'modalDetective',
    sentence: 'You ___ sit here if you want.', clueText: 'if you want',
    answer: 'can', acceptedAnswers: ['can', 'may'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Is someone allowed to do this?',
    meaningHint: 'If you want means it is allowed.',
    formHint: 'Use can or may to give permission.',
    explanation: 'If you want is the clue. This is permission, so use can.',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might means maybe. If you want gives permission, so use can.' },
    tags: ['modal', 'can', 'permission'], difficulty: 1
  },
  {
    id: 'modal-permission-004', game: 'modalDetective',
    sentence: 'Students ___ use the library after class.', clueText: 'use the library',
    answer: 'can', acceptedAnswers: ['can', 'may'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Are students allowed to do this?',
    meaningHint: 'This sentence tells us what is allowed.',
    formHint: 'Use can to show permission.',
    explanation: 'Use the library is the clue. This is permission, so use can.',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might means maybe it will happen. Can means they are allowed to do it.' },
    tags: ['modal', 'can', 'permission'], difficulty: 2
  },
  {
    id: 'modal-permission-005', game: 'modalDetective',
    sentence: '___ we go to the bathroom?', clueText: 'go to the bathroom',
    answer: 'may', acceptedAnswers: ['may', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Is this asking to be allowed?',
    meaningHint: 'Asking to go to the bathroom is asking permission.',
    formHint: 'Use may (or can) to ask permission.',
    explanation: 'Go to the bathroom is the clue. This is asking permission, so use may.',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might is for maybe, not asking permission.' },
    tags: ['modal', 'may', 'permission'], difficulty: 1
  },
  {
    id: 'modal-permission-006', game: 'modalDetective',
    sentence: 'You ___ play games after you finish your homework.', clueText: 'after you finish',
    answer: 'can', acceptedAnswers: ['can', 'may'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Are they allowed to play?',
    meaningHint: 'They are allowed to play after finishing homework.',
    formHint: 'Use can to give permission.',
    explanation: 'After you finish is the clue. This is giving permission, so use can.',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might means maybe. They are allowed, so use can.' },
    tags: ['modal', 'can', 'permission'], difficulty: 2
  },
  {
    id: 'modal-permission-007', game: 'modalDetective',
    sentence: 'Mom, ___ I watch TV now?', clueText: 'Mom',
    answer: 'can', acceptedAnswers: ['can', 'may'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Is a child asking to be allowed?',
    meaningHint: 'Asking Mom is asking for permission.',
    formHint: 'Use can (or may) to ask permission.',
    explanation: 'Mom is the clue. This is asking permission, so use can.',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might is for maybe, not for asking Mom.' },
    tags: ['modal', 'can', 'permission'], difficulty: 1
  },
  {
    id: 'modal-permission-008', game: 'modalDetective',
    sentence: 'Visitors ___ take photos inside the museum.', clueText: 'take photos',
    answer: 'may', acceptedAnswers: ['may', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'permission', scenarioLabel: 'Permission',
    clueQuestion: 'Is this an allowed rule?',
    meaningHint: 'This gives visitors permission to take photos.',
    formHint: 'Use may (or can) for formal permission.',
    explanation: 'Take photos is the clue. This is permission, so use may.',
    confusionTargets: ['might'],
    distractorRationale: { 'might': 'Might means maybe. May means they are allowed.' },
    tags: ['modal', 'may', 'permission'], difficulty: 2
  },

  // POLITE REQUEST (8 items)
  {
    id: 'modal-request-001', game: 'modalDetective',
    sentence: '___ you help me with this box, please?', clueText: 'help me',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is someone asking politely for help?',
    meaningHint: 'Asking someone to help you is a request.',
    formHint: 'Use could to ask politely.',
    explanation: 'Help me is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'May I is for permission. Could you is for asking someone to do something.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 1
  },
  {
    id: 'modal-request-002', game: 'modalDetective',
    sentence: '___ you open the door for me, please?', clueText: 'open the door',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is someone asking politely for help?',
    meaningHint: 'Asking someone else to open the door is a request.',
    formHint: 'Use could you to ask politely.',
    explanation: 'Open the door is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'May I is for permission. Could you is for asking someone to help.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 1
  },
  {
    id: 'modal-request-003', game: 'modalDetective',
    sentence: '___ you speak more slowly, please?', clueText: 'speak more slowly',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is this a polite request?',
    meaningHint: 'You want them to speak slowly.',
    formHint: 'Use could you to be polite.',
    explanation: 'Speak more slowly is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'May I is for permission. Could you is for requests.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 2
  },
  {
    id: 'modal-request-004', game: 'modalDetective',
    sentence: '___ you pass me the salt?', clueText: 'pass me the salt',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is someone asking for help politely?',
    meaningHint: 'Asking for the salt is a request.',
    formHint: 'Use could you for polite requests.',
    explanation: 'Pass me the salt is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'You cannot say May you pass me the salt. Use could you.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 2
  },
  {
    id: 'modal-request-005', game: 'modalDetective',
    sentence: '___ you lend me your pencil, please?', clueText: 'lend me your pencil',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is this asking someone to do something?',
    meaningHint: 'Asking someone to lend a pencil is a request.',
    formHint: 'Use could you to ask politely.',
    explanation: 'Lend me your pencil is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'May I borrow your pencil is okay, but this is ___ you lend me, so use could you.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 2
  },
  {
    id: 'modal-request-006', game: 'modalDetective',
    sentence: '___ you turn down the music?', clueText: 'turn down the music',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is someone politely asking for a change?',
    meaningHint: 'Asking someone to turn down music is a request.',
    formHint: 'Use could you.',
    explanation: 'Turn down the music is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'Use could you for requests.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 1
  },
  {
    id: 'modal-request-007', game: 'modalDetective',
    sentence: '___ you show me the way to the station?', clueText: 'show me the way',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is someone asking for directions politely?',
    meaningHint: 'Asking for directions is a polite request.',
    formHint: 'Use could you.',
    explanation: 'Show me the way is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'May you is wrong for requests. Use could you.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 2
  },
  {
    id: 'modal-request-008', game: 'modalDetective',
    sentence: '___ you hold my bag for a minute?', clueText: 'hold my bag',
    answer: 'could', acceptedAnswers: ['could', 'can'], options: ['can', 'could', 'may', 'might'],
    scenario: 'polite_request', scenarioLabel: 'Polite Request',
    clueQuestion: 'Is this asking someone to help?',
    meaningHint: 'Asking someone to hold a bag is a request.',
    formHint: 'Use could you.',
    explanation: 'Hold my bag is the clue. This is a polite request, so use could.',
    confusionTargets: ['may'],
    distractorRationale: { 'may': 'Use could you to ask someone to do something.' },
    tags: ['modal', 'could', 'polite_request'], difficulty: 1
  },

  // POSSIBILITY (12 items)
  {
    id: 'modal-possibility-001', game: 'modalDetective',
    sentence: 'She ___ be at home, but I am not sure.', clueText: 'not sure',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Are we guessing because we are not sure?',
    meaningHint: 'Not sure means it is only a possibility.',
    formHint: 'Use might, may, or could for maybe.',
    explanation: 'Not sure is the clue. This is a possibility, so use might.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability. Might is for maybe.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 1
  },
  {
    id: 'modal-possibility-002', game: 'modalDetective',
    sentence: 'It is cloudy, so it ___ rain later.', clueText: 'cloudy',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is the speaker saying maybe?',
    meaningHint: 'Cloudy means rain is possible, but not 100%.',
    formHint: 'Use might, may, or could.',
    explanation: 'Cloudy is the clue. This is a possibility, so use might.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability or permission. Use might for maybe.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 1
  },
  {
    id: 'modal-possibility-003', game: 'modalDetective',
    sentence: 'The answer ___ be B, but I need to check.', clueText: 'need to check',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is the speaker uncertain?',
    meaningHint: 'Need to check means they are not sure.',
    formHint: 'Use might for maybe.',
    explanation: 'Need to check is the clue. This is a possibility, so use might.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Use might because they are not sure.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 2
  },
  {
    id: 'modal-possibility-004', game: 'modalDetective',
    sentence: 'He ___ come to the party, but he is still sick.', clueText: 'still sick',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['must', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is the future uncertain?',
    meaningHint: 'He is sick, so coming is just a maybe.',
    formHint: 'Use might for maybe.',
    explanation: 'Still sick is the clue. This is a possibility, so use might.',
    confusionTargets: ['must'],
    distractorRationale: { 'must': 'Must is for a strong rule. If he is sick, he doesn\'t have to come.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 2
  },
  {
    id: 'modal-possibility-005', game: 'modalDetective',
    sentence: 'Perhaps we ___ find the lost dog near the park.', clueText: 'Perhaps',
    answer: 'could', acceptedAnswers: ['could', 'may', 'might'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Does the clue mean maybe?',
    meaningHint: 'Perhaps means it is possible.',
    formHint: 'Use could, may, or might for possibility.',
    explanation: 'Perhaps is the clue. This is a possibility, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability. Could can mean maybe.' },
    tags: ['modal', 'could', 'possibility'], difficulty: 2
  },
  {
    id: 'modal-possibility-006', game: 'modalDetective',
    sentence: 'I don\'t know where my keys are. They ___ be in the car.', clueText: 'don\'t know',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['must', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is the speaker guessing?',
    meaningHint: 'Don\'t know means this is a guess.',
    formHint: 'Use might for a guess.',
    explanation: 'Don\'t know is the clue. This is a possibility, so use might.',
    confusionTargets: ['must'],
    distractorRationale: { 'must': 'Must means 100% sure. Don\'t know means maybe, so use might.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 2
  },
  {
    id: 'modal-possibility-007', game: 'modalDetective',
    sentence: 'Take an umbrella. It ___ rain this afternoon.', clueText: 'Take an umbrella',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is it possible that it will rain?',
    meaningHint: 'Taking an umbrella means rain is possible.',
    formHint: 'Use might for possibility.',
    explanation: 'Take an umbrella is the clue. This is a possibility, so use might.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability. Might is for maybe.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 1
  },
  {
    id: 'modal-possibility-008', game: 'modalDetective',
    sentence: 'She hasn\'t decided yet, but she ___ study art.', clueText: 'hasn\'t decided yet',
    answer: 'may', acceptedAnswers: ['may', 'might', 'could'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is she still thinking about it?',
    meaningHint: 'Hasn\'t decided yet means maybe she will.',
    formHint: 'Use may or might for maybe.',
    explanation: 'Hasn\'t decided yet is the clue. This is a possibility, so use may.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability. May is for possibility.' },
    tags: ['modal', 'may', 'possibility'], difficulty: 2
  },
  {
    id: 'modal-possibility-009', game: 'modalDetective',
    sentence: 'If we hurry, we ___ catch the early bus.', clueText: 'If we hurry',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['must', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is it possible to catch the bus?',
    meaningHint: 'If we hurry gives a chance or possibility.',
    formHint: 'Use might for possibility.',
    explanation: 'If we hurry is the clue. This is a possibility, so use might.',
    confusionTargets: ['must'],
    distractorRationale: { 'must': 'Must is for rules. Might is for a chance or possibility.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 2
  },
  {
    id: 'modal-possibility-010', game: 'modalDetective',
    sentence: 'I haven\'t seen Tom. He ___ be in the garden.', clueText: 'haven\'t seen',
    answer: 'could', acceptedAnswers: ['could', 'may', 'might'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Are we guessing where he is?',
    meaningHint: 'Haven\'t seen him means we are guessing.',
    formHint: 'Use could for a possible guess.',
    explanation: 'Haven\'t seen is the clue. This is a possibility, so use could.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability. Could is for a guess or maybe.' },
    tags: ['modal', 'could', 'possibility'], difficulty: 2
  },
  {
    id: 'modal-possibility-011', game: 'modalDetective',
    sentence: 'Don\'t eat that old bread. You ___ get sick.', clueText: 'old bread',
    answer: 'might', acceptedAnswers: ['might', 'may', 'could'], options: ['can', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is there a chance of getting sick?',
    meaningHint: 'Old bread creates a possibility of sickness.',
    formHint: 'Use might for possibility.',
    explanation: 'Old bread is the clue. This is a possibility, so use might.',
    confusionTargets: ['can'],
    distractorRationale: { 'can': 'Can is for ability. Might is for a bad possibility.' },
    tags: ['modal', 'might', 'possibility'], difficulty: 1
  },
  {
    id: 'modal-possibility-012', game: 'modalDetective',
    sentence: 'I am looking for my phone. It ___ be under the bed.', clueText: 'looking for',
    answer: 'may', acceptedAnswers: ['may', 'might', 'could'], options: ['must', 'could', 'may', 'might'],
    scenario: 'possibility', scenarioLabel: 'Possibility',
    clueQuestion: 'Is the speaker guessing where it is?',
    meaningHint: 'Looking for it means they don\'t know, so it is a guess.',
    formHint: 'Use may or might for a guess.',
    explanation: 'Looking for is the clue. This is a possibility, so use may.',
    confusionTargets: ['must'],
    distractorRationale: { 'must': 'Must means 100% sure. They are looking for it, so it is just maybe.' },
    tags: ['modal', 'may', 'possibility'], difficulty: 2
  },

  // SUGGESTION (6 items)
  {
    id: 'modal-suggestion-001', game: 'modalDetective',
    sentence: 'If you are bored, you ___ read a comic book.', clueText: 'If you are bored',
    answer: 'could', options: ['must', 'could', 'have to', 'had to'],
    scenario: 'suggestion', scenarioLabel: 'Suggestion',
    clueQuestion: 'Is this one possible idea?',
    meaningHint: 'If you are bored is a setup for an idea.',
    formHint: 'Use could for a gentle suggestion.',
    explanation: 'If you are bored is the clue. This is a suggestion, so use could.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is for strong rules. Reading a comic is just an idea.', 'have to': 'Have to is a rule, not an idea.' },
    tags: ['modal', 'could', 'suggestion'], difficulty: 1
  },
  {
    id: 'modal-suggestion-002', game: 'modalDetective',
    sentence: 'We ___ make a card for Mom.', clueText: 'make a card',
    answer: 'could', options: ['must', 'could', 'have to', 'had to'],
    scenario: 'suggestion', scenarioLabel: 'Suggestion',
    clueQuestion: 'Is this a suggested idea?',
    meaningHint: 'Making a card is a nice idea.',
    formHint: 'Use could to suggest an idea.',
    explanation: 'Make a card is the clue. This is a suggestion, so use could.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is a rule. This is just a nice idea.', 'have to': 'Have to means no choice. Could means it is an idea.' },
    tags: ['modal', 'could', 'suggestion'], difficulty: 1
  },
  {
    id: 'modal-suggestion-003', game: 'modalDetective',
    sentence: 'For dinner, we ___ order pizza.', clueText: 'For dinner',
    answer: 'could', options: ['must', 'could', 'have to', 'had to'],
    scenario: 'suggestion', scenarioLabel: 'Suggestion',
    clueQuestion: 'Is this an idea for dinner?',
    meaningHint: 'Ordering pizza is one choice for dinner.',
    formHint: 'Use could for a suggestion.',
    explanation: 'For dinner is the clue. This is a suggestion, so use could.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must means it is a strong rule. Pizza is just an idea.', 'have to': 'Have to means a rule.' },
    tags: ['modal', 'could', 'suggestion'], difficulty: 1
  },
  {
    id: 'modal-suggestion-004', game: 'modalDetective',
    sentence: 'If it rains, we ___ play games inside.', clueText: 'If it rains',
    answer: 'could', options: ['must', 'could', 'have to', 'had to'],
    scenario: 'suggestion', scenarioLabel: 'Suggestion',
    clueQuestion: 'Is this an idea for what to do?',
    meaningHint: 'If it rains gives us a chance to think of an idea.',
    formHint: 'Use could to suggest an idea.',
    explanation: 'If it rains is the clue. This is a suggestion, so use could.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is for rules. Could is for a friendly idea.', 'have to': 'Have to is for duties.' },
    tags: ['modal', 'could', 'suggestion'], difficulty: 2
  },
  {
    id: 'modal-suggestion-005', game: 'modalDetective',
    sentence: 'To save money, you ___ walk to school.', clueText: 'To save money',
    answer: 'could', options: ['must', 'could', 'have to', 'had to'],
    scenario: 'suggestion', scenarioLabel: 'Suggestion',
    clueQuestion: 'Is this advice or an idea?',
    meaningHint: 'To save money is advice, not a strict rule.',
    formHint: 'Use could for an idea or advice.',
    explanation: 'To save money is the clue. This is a suggestion, so use could.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is for rules. Walking is just one idea.', 'have to': 'Have to is for rules.' },
    tags: ['modal', 'could', 'suggestion'], difficulty: 2
  },
  {
    id: 'modal-suggestion-006', game: 'modalDetective',
    sentence: 'We ___ go to the park later if you want.', clueText: 'if you want',
    answer: 'could', options: ['must', 'could', 'have to', 'had to'],
    scenario: 'suggestion', scenarioLabel: 'Suggestion',
    clueQuestion: 'Is this an idea they can choose?',
    meaningHint: 'If you want means it is a choice or idea.',
    formHint: 'Use could for an idea.',
    explanation: 'If you want is the clue. This is a suggestion, so use could.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is for a rule. If you want means it is just an idea.', 'have to': 'Have to is for rules.' },
    tags: ['modal', 'could', 'suggestion'], difficulty: 1
  },

  // OBLIGATION / RULE (6 items)
  {
    id: 'modal-obligation-001', game: 'modalDetective',
    sentence: 'You ___ stop when the traffic light is red.', clueText: 'traffic light is red',
    answer: 'must', acceptedAnswers: ['must', 'have to'], options: ['can', 'could', 'must', 'might'],
    scenario: 'obligation', scenarioLabel: 'Obligation / Rule',
    clueQuestion: 'Is this a strong rule or law?',
    meaningHint: 'A red traffic light is a law.',
    formHint: 'Use must for a strong rule.',
    explanation: 'Traffic light is red is the clue. This is a rule, so use must.',
    confusionTargets: ['can', 'might'],
    distractorRationale: { 'can': 'Can is for ability. Stopping at a red light is a rule, so use must.', 'might': 'Might is for maybe. A red light is not maybe.' },
    tags: ['modal', 'must', 'obligation'], difficulty: 1
  },
  {
    id: 'modal-obligation-002', game: 'modalDetective',
    sentence: 'Students ___ wear a uniform to school.', clueText: 'wear a uniform',
    answer: 'have to', acceptedAnswers: ['have to', 'must'], options: ['can', 'could', 'have to', 'might'],
    scenario: 'obligation', scenarioLabel: 'Obligation / Rule',
    clueQuestion: 'Is this a school rule?',
    meaningHint: 'Wearing a uniform is a school rule.',
    formHint: 'Use have to for a rule.',
    explanation: 'Wear a uniform is the clue. This is a rule, so use have to.',
    confusionTargets: ['can', 'might'],
    distractorRationale: { 'can': 'Can is for permission. Have to is for rules.', 'might': 'Might is for maybe.' },
    tags: ['modal', 'have_to', 'obligation'], difficulty: 1
  },
  {
    id: 'modal-obligation-003', game: 'modalDetective',
    sentence: 'You ___ wash your hands before eating.', clueText: 'before eating',
    answer: 'must', acceptedAnswers: ['must', 'have to'], options: ['can', 'could', 'must', 'might'],
    scenario: 'obligation', scenarioLabel: 'Obligation / Rule',
    clueQuestion: 'Is this a strong health rule?',
    meaningHint: 'Washing hands is an important duty.',
    formHint: 'Use must for strong advice or a rule.',
    explanation: 'Before eating is the clue. This is a strong rule, so use must.',
    confusionTargets: ['can', 'might'],
    distractorRationale: { 'can': 'Can means you have a choice. Must means it is a rule.', 'might': 'Might means maybe.' },
    tags: ['modal', 'must', 'obligation'], difficulty: 1
  },
  {
    id: 'modal-obligation-004', game: 'modalDetective',
    sentence: 'I ___ finish my homework before I can play.', clueText: 'before I can play',
    answer: 'have to', acceptedAnswers: ['have to', 'must'], options: ['can', 'could', 'have to', 'might'],
    scenario: 'obligation', scenarioLabel: 'Obligation / Rule',
    clueQuestion: 'Is this a duty or rule?',
    meaningHint: 'Before playing shows a duty you must do first.',
    formHint: 'Use have to for a duty.',
    explanation: 'Before I can play is the clue. This is a duty, so use have to.',
    confusionTargets: ['can', 'might'],
    distractorRationale: { 'can': 'Can is for permission. Have to is for a duty.', 'might': 'Might means maybe.' },
    tags: ['modal', 'have_to', 'obligation'], difficulty: 2
  },
  {
    id: 'modal-obligation-005', game: 'modalDetective',
    sentence: 'You ___ be quiet in the library.', clueText: 'in the library',
    answer: 'must', acceptedAnswers: ['must', 'have to'], options: ['can', 'could', 'must', 'might'],
    scenario: 'obligation', scenarioLabel: 'Obligation / Rule',
    clueQuestion: 'Is this a rule of a place?',
    meaningHint: 'The library has a strict rule to be quiet.',
    formHint: 'Use must for strict rules.',
    explanation: 'In the library is the clue. This is a rule, so use must.',
    confusionTargets: ['can', 'might'],
    distractorRationale: { 'can': 'Can means you have a choice. Must means it is a strict rule.', 'might': 'Might means maybe.' },
    tags: ['modal', 'must', 'obligation'], difficulty: 1
  },
  {
    id: 'modal-obligation-006', game: 'modalDetective',
    sentence: 'We ___ wake up early tomorrow for the flight.', clueText: 'for the flight',
    answer: 'have to', acceptedAnswers: ['have to', 'must'], options: ['can', 'could', 'have to', 'might'],
    scenario: 'obligation', scenarioLabel: 'Obligation / Rule',
    clueQuestion: 'Is this necessary?',
    meaningHint: 'Catching a flight makes waking up early a necessity.',
    formHint: 'Use have to for necessary actions.',
    explanation: 'For the flight is the clue. This is necessary, so use have to.',
    confusionTargets: ['can', 'might'],
    distractorRationale: { 'can': 'Can is for ability. Have to is for when you have no choice.', 'might': 'Might means maybe.' },
    tags: ['modal', 'have_to', 'obligation'], difficulty: 2
  },

  // PAST OBLIGATION (4 items)
  {
    id: 'modal-pastobligation-001', game: 'modalDetective',
    sentence: 'Yesterday, I ___ clean my room.', clueText: 'Yesterday',
    answer: 'had to', options: ['must', 'have to', 'had to', 'might'],
    scenario: 'past_obligation', scenarioLabel: 'Past Obligation',
    clueQuestion: 'Is this a duty in the past?',
    meaningHint: 'Yesterday means this was a duty in the past.',
    formHint: 'Use had to for a past duty.',
    explanation: 'Yesterday is the clue. This is a past duty, so use had to.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must has no past form. Use had to.', 'have to': 'Have to is for now. Yesterday means had to.' },
    tags: ['modal', 'had_to', 'past_obligation'], difficulty: 2
  },
  {
    id: 'modal-pastobligation-002', game: 'modalDetective',
    sentence: 'The bus was late, so we ___ walk home.', clueText: 'was late',
    answer: 'had to', options: ['must', 'have to', 'had to', 'might'],
    scenario: 'past_obligation', scenarioLabel: 'Past Obligation',
    clueQuestion: 'Was this necessary in the past?',
    meaningHint: 'Was late shows this happened in the past.',
    formHint: 'Use had to for a necessary action in the past.',
    explanation: 'Was late is the clue. This is a past duty, so use had to.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is for now. Use had to for the past.', 'have to': 'Have to is for now. The bus was late, so use had to.' },
    tags: ['modal', 'had_to', 'past_obligation'], difficulty: 2
  },
  {
    id: 'modal-pastobligation-003', game: 'modalDetective',
    sentence: 'Last night, she ___ do a lot of homework.', clueText: 'Last night',
    answer: 'had to', options: ['must', 'have to', 'had to', 'might'],
    scenario: 'past_obligation', scenarioLabel: 'Past Obligation',
    clueQuestion: 'Was this a duty in the past?',
    meaningHint: 'Last night tells us it is in the past.',
    formHint: 'Use had to for a past rule or duty.',
    explanation: 'Last night is the clue. This is a past duty, so use had to.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is not used for the past. Use had to.', 'have to': 'Have to is for now.' },
    tags: ['modal', 'had_to', 'past_obligation'], difficulty: 1
  },
  {
    id: 'modal-pastobligation-004', game: 'modalDetective',
    sentence: 'He broke his glasses, so he ___ buy new ones.', clueText: 'broke',
    answer: 'had to', options: ['must', 'have to', 'had to', 'might'],
    scenario: 'past_obligation', scenarioLabel: 'Past Obligation',
    clueQuestion: 'Was this necessary after something broke?',
    meaningHint: 'Broke is in the past, so the duty is in the past.',
    formHint: 'Use had to for a necessary action in the past.',
    explanation: 'Broke is the clue. This is a past duty, so use had to.',
    confusionTargets: ['must', 'have to'],
    distractorRationale: { 'must': 'Must is for now. Use had to for the past.', 'have to': 'Have to is for now.' },
    tags: ['modal', 'had_to', 'past_obligation'], difficulty: 2
  }
];
