export const grammarDetectiveData = [
  // ==========================================
  // MODAL DETECTIVE (18 questions)
  // ==========================================
  {
    id: 'modal-001',
    game: 'modalDetective',
    sentence: 'Students ___ wear uniforms at school every day.',
    clueText: 'every day',
    answer: 'have to',
    acceptedAnswers: ['have to', 'must'],
    options: ['have to', 'had to', 'must', 'may', 'might', 'could'],
    explanation: 'This is a regular school duty. Use have to or must + base verb.',
    concept: 'obligation',
    tags: ['modal', 'obligation', 'routine', 'base_verb_after_modal'],
    difficulty: 1
  },
  {
    id: 'modal-002',
    game: 'modalDetective',
    sentence: 'It is cloudy. It ___ rain later, but I am not sure.',
    clueText: 'not sure',
    answer: 'might',
    acceptedAnswers: ['might', 'may', 'could'],
    options: ['have to', 'must', 'might', 'may', 'could', 'had to'],
    explanation: 'When you are not sure, use might, may, or could.',
    concept: 'possibility',
    tags: ['modal', 'possibility', 'uncertainty'],
    difficulty: 1
  },
  {
    id: 'modal-003',
    game: 'modalDetective',
    sentence: 'Yesterday, the car broke down, so we ___ walk home.',
    clueText: 'Yesterday',
    answer: 'had to',
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: 'This is a past duty because it happened yesterday. Use had to.',
    concept: 'past_obligation',
    tags: ['modal', 'past_obligation', 'past_time'],
    difficulty: 2
  },
  {
    id: 'modal-004',
    game: 'modalDetective',
    sentence: 'The sign says you ___ stop at the red light.',
    clueText: 'sign says',
    answer: 'must',
    acceptedAnswers: ['must', 'have to'],
    options: ['have to', 'had to', 'must', 'may', 'might', 'could'],
    explanation: 'A sign is a strong rule. Use must or have to.',
    concept: 'obligation',
    tags: ['modal', 'obligation', 'rule'],
    difficulty: 1
  },
  {
    id: 'modal-005',
    game: 'modalDetective',
    sentence: 'Where is Mom? She ___ be in the kitchen, maybe cooking.',
    clueText: 'maybe',
    answer: 'may',
    acceptedAnswers: ['may', 'might', 'could'],
    options: ['have to', 'had to', 'must', 'may', 'might', 'could'],
    explanation: '"Maybe" means it is a possibility, not a rule. Use may, might, or could.',
    concept: 'possibility',
    tags: ['modal', 'possibility'],
    difficulty: 1
  },
  {
    id: 'modal-006',
    game: 'modalDetective',
    sentence: 'Last night, I ___ finish my homework before playing games.',
    clueText: 'Last night',
    answer: 'had to',
    options: ['have to', 'must', 'had to', 'might', 'may', 'could'],
    explanation: 'It was a rule in the past. Use had to.',
    concept: 'past_obligation',
    tags: ['modal', 'past_obligation'],
    difficulty: 1
  },
  {
    id: 'modal-007',
    game: 'modalDetective',
    sentence: 'If you want to pass the test, you ___ study hard.',
    clueText: 'want to pass',
    answer: 'must',
    acceptedAnswers: ['must', 'have to'],
    options: ['have to', 'had to', 'must', 'may', 'might', 'could'],
    explanation: 'This is a strong necessity for a good result. Use must or have to.',
    concept: 'obligation',
    tags: ['modal', 'obligation', 'necessity'],
    difficulty: 2
  },
  {
    id: 'modal-008',
    game: 'modalDetective',
    sentence: 'I lost my keys. They ___ be under the sofa, but I need to check.',
    clueText: 'need to check',
    answer: 'could',
    acceptedAnswers: ['could', 'might', 'may'],
    options: ['must', 'have to', 'had to', 'may', 'might', 'could'],
    explanation: 'Since you need to check, it means you are not sure. Use could, might, or may.',
    concept: 'possibility',
    tags: ['modal', 'possibility'],
    difficulty: 2
  },
  {
    id: 'modal-009',
    game: 'modalDetective',
    sentence: 'When I was younger, I ___ go to bed at 8 PM.',
    clueText: 'was younger',
    answer: 'had to',
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: 'This is a past rule because it happened when you were younger. Use had to.',
    concept: 'past_obligation',
    tags: ['modal', 'past_obligation'],
    difficulty: 2
  },
  {
    id: 'modal-010',
    game: 'modalDetective',
    sentence: 'Look at the time! We ___ leave now or we will miss the bus.',
    clueText: 'miss the bus',
    answer: 'have to',
    acceptedAnswers: ['have to', 'must'],
    options: ['have to', 'had to', 'must', 'may', 'might', 'could'],
    explanation: 'This is a strong need right now. Use have to or must.',
    concept: 'obligation',
    tags: ['modal', 'obligation'],
    difficulty: 2
  },
  {
    id: 'modal-011',
    game: 'modalDetective',
    sentence: 'He is studying really hard. He ___ pass the exam, but who knows?',
    clueText: 'who knows',
    answer: 'might',
    acceptedAnswers: ['might', 'may', 'could'],
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: '"Who knows?" shows uncertainty. Use might, may, or could.',
    concept: 'possibility',
    tags: ['modal', 'possibility'],
    difficulty: 2
  },
  {
    id: 'modal-012',
    game: 'modalDetective',
    sentence: 'Last week, they ___ clean the whole house for the party.',
    clueText: 'Last week',
    answer: 'had to',
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: 'Because it was last week, it is a past duty. Use had to.',
    concept: 'past_obligation',
    tags: ['modal', 'past_obligation'],
    difficulty: 1
  },
  {
    id: 'modal-013',
    game: 'modalDetective',
    sentence: 'You ___ wash your hands before eating dinner.',
    clueText: 'before eating',
    answer: 'must',
    acceptedAnswers: ['must', 'have to'],
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: 'This is an important hygiene rule. Use must or have to.',
    concept: 'obligation',
    tags: ['modal', 'obligation', 'rule'],
    difficulty: 1
  },
  {
    id: 'modal-014',
    game: 'modalDetective',
    sentence: 'We ___ go to the park tomorrow if the weather is nice.',
    clueText: 'if',
    answer: 'may',
    acceptedAnswers: ['may', 'might', 'could'],
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: '"If" means it is conditional and uncertain. Use may, might, or could.',
    concept: 'possibility',
    tags: ['modal', 'possibility', 'conditional'],
    difficulty: 2
  },
  {
    id: 'modal-015',
    game: 'modalDetective',
    sentence: 'Because he was sick yesterday, he ___ stay in bed.',
    clueText: 'yesterday',
    answer: 'had to',
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: 'This was a necessity in the past. Use had to.',
    concept: 'past_obligation',
    tags: ['modal', 'past_obligation'],
    difficulty: 1
  },
  {
    id: 'modal-016',
    game: 'modalDetective',
    sentence: 'To enter the swimming pool, you ___ wear a swimming cap.',
    clueText: 'To enter',
    answer: 'must',
    acceptedAnswers: ['must', 'have to'],
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: 'This is a condition or rule. Use must or have to.',
    concept: 'obligation',
    tags: ['modal', 'obligation', 'rule'],
    difficulty: 2
  },
  {
    id: 'modal-017',
    game: 'modalDetective',
    sentence: 'That dog is looking around. It ___ be lost, perhaps.',
    clueText: 'perhaps',
    answer: 'could',
    acceptedAnswers: ['could', 'might', 'may'],
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: '"Perhaps" means it is a guess. Use could, might, or may.',
    concept: 'possibility',
    tags: ['modal', 'possibility'],
    difficulty: 2
  },
  {
    id: 'modal-018',
    game: 'modalDetective',
    sentence: 'When the fire alarm rang, everyone ___ leave the building immediately.',
    clueText: 'rang',
    answer: 'had to',
    options: ['have to', 'must', 'had to', 'may', 'might', 'could'],
    explanation: 'The alarm "rang" in the past, so it was a past duty. Use had to.',
    concept: 'past_obligation',
    tags: ['modal', 'past_obligation'],
    difficulty: 3
  },

  // ==========================================
  // ACTION FREEZE DETECTIVE (18 questions)
  // ==========================================
  {
    id: 'freeze-001',
    game: 'actionFreezeDetective',
    sentence: 'I ___ TV when the phone rang.',
    clueText: 'when',
    answer: 'was watching',
    options: ['watched', 'was watching', 'were watching', 'am watching'],
    explanation: 'The long action "was watching" was interrupted "when" the phone rang.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'when'],
    difficulty: 1,
    subject: 'I',
    baseVerb: 'watch',
    longAction: 'watch TV',
    interruptingAction: 'phone rang',
    auxiliary: 'was'
  },
  {
    id: 'freeze-002',
    game: 'actionFreezeDetective',
    sentence: 'While we ___, it started to rain.',
    clueText: 'While',
    answer: 'were playing',
    options: ['played', 'were playing', 'was playing', 'are playing'],
    explanation: '"While" shows a long background action. Use "were playing" for "we".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while', 'subject_agreement'],
    difficulty: 1,
    subject: 'we',
    baseVerb: 'play',
    longAction: 'play',
    interruptingAction: 'started to rain',
    auxiliary: 'were'
  },
  {
    id: 'freeze-003',
    game: 'actionFreezeDetective',
    sentence: 'She ___ her bike at 5 PM yesterday.',
    clueText: 'at 5 PM yesterday',
    answer: 'was riding',
    options: ['rode', 'was riding', 'were riding', 'is riding'],
    explanation: 'An exact time in the past shows an action in progress. Use "was riding".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'exact_time'],
    difficulty: 2,
    subject: 'She',
    baseVerb: 'ride',
    longAction: 'ride her bike',
    auxiliary: 'was'
  },
  {
    id: 'freeze-004',
    game: 'actionFreezeDetective',
    sentence: 'They ___ dinner when the lights went out.',
    clueText: 'when',
    answer: 'were eating',
    options: ['ate', 'was eating', 'were eating', 'eat'],
    explanation: 'The long action "were eating" was interrupted. Use "were" for "They".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'subject_agreement'],
    difficulty: 1,
    subject: 'They',
    baseVerb: 'eat',
    longAction: 'eat dinner',
    interruptingAction: 'lights went out',
    auxiliary: 'were'
  },
  {
    id: 'freeze-005',
    game: 'actionFreezeDetective',
    sentence: 'While he ___ a book, his sister was listening to music.',
    clueText: 'While',
    answer: 'was reading',
    options: ['read', 'was reading', 'were reading', 'reads'],
    explanation: 'Two long actions happening at the same time. Use "was reading" for "he".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'parallel_actions'],
    difficulty: 2,
    subject: 'he',
    baseVerb: 'read',
    longAction: 'read a book',
    auxiliary: 'was'
  },
  {
    id: 'freeze-006',
    game: 'actionFreezeDetective',
    sentence: 'You ___ too fast when the police stopped you.',
    clueText: 'when',
    answer: 'were driving',
    options: ['drove', 'was driving', 'were driving', 'drive'],
    explanation: 'The driving was interrupted. Use "were driving" with "You".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'subject_agreement'],
    difficulty: 2,
    subject: 'You',
    baseVerb: 'drive',
    longAction: 'drive too fast',
    interruptingAction: 'police stopped',
    auxiliary: 'were'
  },
  {
    id: 'freeze-007',
    game: 'actionFreezeDetective',
    sentence: 'I dropped my keys while I ___ to the bus stop.',
    clueText: 'while',
    answer: 'was walking',
    options: ['walked', 'was walking', 'were walking', 'am walking'],
    explanation: 'The walking was the long action happening when the keys dropped.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'while'],
    difficulty: 1,
    subject: 'I',
    baseVerb: 'walk',
    longAction: 'walk to the bus stop',
    interruptingAction: 'dropped my keys',
    auxiliary: 'was'
  },
  {
    id: 'freeze-008',
    game: 'actionFreezeDetective',
    sentence: 'You ___ at 8 o\'clock last night.',
    clueText: 'at 8 o\'clock',
    answer: 'were studying',
    options: ['studied', 'was studying', 'were studying', 'are studying'],
    explanation: 'Asking about an action in progress at a specific past time. Use "were studying".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'exact_time'],
    difficulty: 3,
    subject: 'you',
    baseVerb: 'study',
    longAction: 'study',
    auxiliary: 'were'
  },
  {
    id: 'freeze-009',
    game: 'actionFreezeDetective',
    sentence: 'The dog ___ loudly when someone knocked on the door.',
    clueText: 'when',
    answer: 'was barking',
    options: ['barked', 'was barking', 'were barking', 'barks'],
    explanation: 'The long action of barking was interrupted by the knock.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption'],
    difficulty: 1,
    subject: 'The dog',
    baseVerb: 'bark',
    longAction: 'bark loudly',
    interruptingAction: 'knocked',
    auxiliary: 'was'
  },
  {
    id: 'freeze-010',
    game: 'actionFreezeDetective',
    sentence: 'While the teacher ___, the students were taking notes.',
    clueText: 'While',
    answer: 'was speaking',
    options: ['spoke', 'was speaking', 'were speaking', 'speaks'],
    explanation: 'Two long actions at the same time. The teacher (singular) uses "was".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'parallel_actions'],
    difficulty: 2,
    subject: 'teacher',
    baseVerb: 'speak',
    longAction: 'speak',
    auxiliary: 'was'
  },
  {
    id: 'freeze-011',
    game: 'actionFreezeDetective',
    sentence: 'We ___ for the bus when it started to snow.',
    clueText: 'when',
    answer: 'were waiting',
    options: ['waited', 'was waiting', 'were waiting', 'wait'],
    explanation: 'Waiting is the long background action. "We" uses "were waiting".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'subject_agreement'],
    difficulty: 1,
    subject: 'We',
    baseVerb: 'wait',
    longAction: 'wait for the bus',
    interruptingAction: 'started to snow',
    auxiliary: 'were'
  },
  {
    id: 'freeze-012',
    game: 'actionFreezeDetective',
    sentence: 'He broke his leg while he ___ football.',
    clueText: 'while',
    answer: 'was playing',
    options: ['played', 'was playing', 'were playing', 'is playing'],
    explanation: 'Playing football was the long action that got interrupted.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while', 'interruption'],
    difficulty: 1,
    subject: 'he',
    baseVerb: 'play',
    longAction: 'play football',
    interruptingAction: 'broke his leg',
    auxiliary: 'was'
  },
  {
    id: 'freeze-013',
    game: 'actionFreezeDetective',
    sentence: 'My friends ___ a movie when I arrived.',
    clueText: 'when',
    answer: 'were watching',
    options: ['watched', 'was watching', 'were watching', 'are watching'],
    explanation: '"Friends" is plural, so use "were watching" as the background action.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'subject_agreement', 'interruption'],
    difficulty: 2,
    subject: 'friends',
    baseVerb: 'watch',
    longAction: 'watch a movie',
    interruptingAction: 'arrived',
    auxiliary: 'were'
  },
  {
    id: 'freeze-014',
    game: 'actionFreezeDetective',
    sentence: 'At midnight, everyone ___ deeply.',
    clueText: 'At midnight',
    answer: 'was sleeping',
    options: ['slept', 'was sleeping', 'were sleeping', 'sleeps'],
    explanation: '"Everyone" takes a singular verb. The specific time indicates an action in progress.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'exact_time', 'subject_agreement'],
    difficulty: 3,
    subject: 'everyone',
    baseVerb: 'sleep',
    longAction: 'sleep deeply',
    auxiliary: 'was'
  },
  {
    id: 'freeze-015',
    game: 'actionFreezeDetective',
    sentence: 'While I was cooking, my brother ___ the table.',
    clueText: 'While',
    answer: 'was setting',
    options: ['set', 'was setting', 'were setting', 'sets'],
    explanation: 'Parallel actions happening at the same time in the past.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'parallel_actions'],
    difficulty: 2,
    subject: 'brother',
    baseVerb: 'set',
    longAction: 'set the table',
    auxiliary: 'was'
  },
  {
    id: 'freeze-016',
    game: 'actionFreezeDetective',
    sentence: 'The baby started crying while they ___ outside.',
    clueText: 'while',
    answer: 'were talking',
    options: ['talked', 'was talking', 'were talking', 'are talking'],
    explanation: 'The talking was the continuous action. "They" uses "were".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while', 'subject_agreement'],
    difficulty: 1,
    subject: 'they',
    baseVerb: 'talk',
    longAction: 'talk outside',
    interruptingAction: 'baby started crying',
    auxiliary: 'were'
  },
  {
    id: 'freeze-017',
    game: 'actionFreezeDetective',
    sentence: 'I saw an accident while I ___ my car.',
    clueText: 'while',
    answer: 'was driving',
    options: ['drove', 'was driving', 'were driving', 'am driving'],
    explanation: 'Driving is the long background action.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while'],
    difficulty: 1,
    subject: 'I',
    baseVerb: 'drive',
    longAction: 'drive my car',
    interruptingAction: 'saw an accident',
    auxiliary: 'was'
  },
  {
    id: 'freeze-018',
    game: 'actionFreezeDetective',
    sentence: 'She ___ her hair when the power went out.',
    clueText: 'when',
    answer: 'was drying',
    options: ['dried', 'was drying', 'were drying', 'dries'],
    explanation: 'The long action of drying hair was interrupted.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption'],
    difficulty: 1,
    subject: 'She',
    baseVerb: 'dry',
    longAction: 'dry her hair',
    interruptingAction: 'power went out',
    auxiliary: 'was'
  },

  // ==========================================
  // FUTURE FORECAST DETECTIVE (18 questions)
  // ==========================================
  {
    id: 'future-001',
    game: 'futureForecastDetective',
    sentence: 'Look at those dark clouds! It ___ rain.',
    clueText: 'dark clouds',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Dark clouds are visible evidence. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 1,
    futureUse: 'visible_evidence',
    subject: 'It',
    auxiliary: 'is'
  },
  {
    id: 'future-002',
    game: 'futureForecastDetective',
    sentence: 'I promise I ___ help you with your homework tonight.',
    clueText: 'promise',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'For a promise, use "will".',
    concept: 'future_forms',
    tags: ['future', 'promise', 'will'],
    difficulty: 1,
    futureUse: 'promise',
    subject: 'I'
  },
  {
    id: 'future-003',
    game: 'futureForecastDetective',
    sentence: 'We have bought the tickets. We ___ fly to Japan next week.',
    clueText: 'bought the tickets',
    answer: 'are going to',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'Having tickets means it is a firm plan. Use "are going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'We',
    auxiliary: 'are'
  },
  {
    id: 'future-004',
    game: 'futureForecastDetective',
    sentence: 'Oh, you dropped your pen. I ___ pick it up for you.',
    clueText: 'dropped your pen',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a quick decision or an offer to help right now. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'quick_decision', 'offer', 'will'],
    difficulty: 2,
    futureUse: 'quick_decision',
    subject: 'I'
  },
  {
    id: 'future-005',
    game: 'futureForecastDetective',
    sentence: 'I think that team ___ win the match today.',
    clueText: 'think',
    answer: 'will',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: '"I think" shows it is an opinion or guess. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'opinion', 'will'],
    difficulty: 1,
    futureUse: 'opinion',
    subject: 'team'
  },
  {
    id: 'future-006',
    game: 'futureForecastDetective',
    sentence: 'She packed her bags because she ___ stay at her grandma\'s house.',
    clueText: 'packed her bags',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Packing bags shows it is a plan. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'she',
    auxiliary: 'is'
  },
  {
    id: 'future-007',
    game: 'futureForecastDetective',
    sentence: 'Watch out! That glass ___ fall off the table!',
    clueText: 'Watch out',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: '"Watch out" means there is immediate visible danger. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 2,
    futureUse: 'visible_evidence',
    subject: 'glass',
    auxiliary: 'is'
  },
  {
    id: 'future-008',
    game: 'futureForecastDetective',
    sentence: 'I am thirsty. I ___ get a glass of water.',
    clueText: 'am thirsty',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a sudden decision made right now. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'quick_decision', 'will'],
    difficulty: 1,
    futureUse: 'quick_decision',
    subject: 'I'
  },
  {
    id: 'future-009',
    game: 'futureForecastDetective',
    sentence: 'We booked a table at the restaurant. We ___ have a family dinner.',
    clueText: 'booked a table',
    answer: 'are going to',
    options: ['will', 'are going to', 'is going to', 'am going to'],
    explanation: 'Booking a table makes it a set plan. Use "are going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'We',
    auxiliary: 'are'
  },
  {
    id: 'future-010',
    game: 'futureForecastDetective',
    sentence: 'Maybe I ___ visit my cousins next summer.',
    clueText: 'Maybe',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: '"Maybe" shows it is just an idea, not a firm plan yet. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'opinion', 'will'],
    difficulty: 2,
    futureUse: 'opinion',
    subject: 'I'
  },
  {
    id: 'future-011',
    game: 'futureForecastDetective',
    sentence: 'The sky is completely clear. It ___ be a beautiful day.',
    clueText: 'completely clear',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'A clear sky is strong evidence. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 2,
    futureUse: 'visible_evidence',
    subject: 'It',
    auxiliary: 'is'
  },
  {
    id: 'future-012',
    game: 'futureForecastDetective',
    sentence: 'Don\'t worry, I ___ not tell anyone your secret.',
    clueText: 'Don\'t worry',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a promise to keep a secret. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'promise', 'will'],
    difficulty: 1,
    futureUse: 'promise',
    subject: 'I'
  },
  {
    id: 'future-013',
    game: 'futureForecastDetective',
    sentence: 'Are you cold? I ___ close the window for you.',
    clueText: 'Are you cold',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a quick offer to help. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'offer', 'will'],
    difficulty: 2,
    futureUse: 'quick_decision',
    subject: 'I'
  },
  {
    id: 'future-014',
    game: 'futureForecastDetective',
    sentence: 'My brother bought flour and eggs. He ___ bake a cake.',
    clueText: 'bought flour',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Buying ingredients is a clear plan to bake. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'evidence', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'He',
    auxiliary: 'is'
  },
  {
    id: 'future-015',
    game: 'futureForecastDetective',
    sentence: 'In the year 2050, I believe people ___ live on Mars.',
    clueText: 'I believe',
    answer: 'will',
    options: ['will', 'are going to', 'is going to', 'am going to'],
    explanation: '"I believe" shows it is an opinion about the distant future. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'opinion', 'will'],
    difficulty: 2,
    futureUse: 'opinion',
    subject: 'people'
  },
  {
    id: 'future-016',
    game: 'futureForecastDetective',
    sentence: 'Look! The runner is way ahead of the others. He ___ win the race.',
    clueText: 'way ahead',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Being way ahead is strong visible evidence right now. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 3,
    futureUse: 'visible_evidence',
    subject: 'He',
    auxiliary: 'is'
  },
  {
    id: 'future-017',
    game: 'futureForecastDetective',
    sentence: 'I ___ study medicine at university when I grow up. That is my dream.',
    clueText: 'my dream',
    answer: 'am going to',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'A strong life ambition or plan takes "going to". Use "am going to" for "I".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 3,
    futureUse: 'plan',
    subject: 'I',
    auxiliary: 'am'
  },
  {
    id: 'future-018',
    game: 'futureForecastDetective',
    sentence: 'The phone is ringing! I ___ answer it.',
    clueText: 'is ringing',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a quick decision made at the moment of speaking. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'quick_decision', 'will'],
    difficulty: 1,
    futureUse: 'quick_decision',
    subject: 'I'
  }
];
