export const grammarDetectiveData = [
  // ==========================================
  // MODAL DETECTIVE (24 questions)
  // ==========================================
  {
    id: 'modal-001',
    game: 'modalDetective',
    sentence: 'I ___ play the piano.',
    clueText: 'play the piano',
    answer: 'can',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Playing the piano is a skill. For ability now, use can.',
    concept: 'ability',
    modalFamily: 'ability_now',
    clueQuestion: 'Is this a skill someone has now?',
    meaningHint: 'This is ability now. Use can.',
    tags: ['modal', 'can', 'ability_now'],
    difficulty: 1
  },
  {
    id: 'modal-002',
    game: 'modalDetective',
    sentence: 'My brother ___ speak English and Vietnamese.',
    clueText: 'speak English and Vietnamese',
    answer: 'can',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Speaking languages is an ability now. Use can.',
    concept: 'ability',
    modalFamily: 'ability_now',
    clueQuestion: 'Is this a skill someone has now?',
    meaningHint: 'This is a current ability. Use can.',
    tags: ['modal', 'can', 'ability_now'],
    difficulty: 1
  },
  {
    id: 'modal-003',
    game: 'modalDetective',
    sentence: 'This bag is heavy, but I ___ carry it.',
    clueText: 'carry it',
    answer: 'can',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'The speaker is able to carry the bag now. Use can.',
    concept: 'ability',
    modalFamily: 'ability_now',
    clueQuestion: 'Can the speaker do it now?',
    meaningHint: 'This is ability now. Use can.',
    tags: ['modal', 'can', 'ability_now'],
    difficulty: 1
  },
  {
    id: 'modal-004',
    game: 'modalDetective',
    sentence: 'She practices every day, so she ___ dance very well.',
    clueText: 'dance very well',
    answer: 'can',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Dancing well is a skill she has now. Use can.',
    concept: 'ability',
    modalFamily: 'ability_now',
    clueQuestion: 'Is this a skill she has now?',
    meaningHint: 'This is ability now. Use can.',
    tags: ['modal', 'can', 'ability_now'],
    difficulty: 2
  },
  {
    id: 'modal-005',
    game: 'modalDetective',
    sentence: 'When I was five, I ___ ride a bike.',
    clueText: 'When I was five',
    answer: 'could',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'When I was five is a past-time clue. For ability in the past, use could.',
    concept: 'ability',
    modalFamily: 'past_ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'This is ability in the past. Use could.',
    tags: ['modal', 'could', 'past_ability'],
    difficulty: 1
  },
  {
    id: 'modal-006',
    game: 'modalDetective',
    sentence: 'My grandfather ___ run fast when he was young.',
    clueText: 'when he was young',
    answer: 'could',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'When he was young means before. For past ability, use could.',
    concept: 'ability',
    modalFamily: 'past_ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'This is past ability. Use could.',
    tags: ['modal', 'could', 'past_ability'],
    difficulty: 1
  },
  {
    id: 'modal-007',
    game: 'modalDetective',
    sentence: 'Before she moved here, she ___ not speak Vietnamese.',
    clueText: 'Before she moved here',
    answer: 'could',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Before she moved here is a past clue. Use could for past ability.',
    concept: 'ability',
    modalFamily: 'past_ability',
    clueQuestion: 'Is this about ability before now?',
    meaningHint: 'This is past ability. Use could.',
    tags: ['modal', 'could', 'past_ability', 'negative_context'],
    difficulty: 2
  },
  {
    id: 'modal-008',
    game: 'modalDetective',
    sentence: 'At age six, he ___ read simple books.',
    clueText: 'At age six',
    answer: 'could',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'At age six points to the past. For ability in the past, use could.',
    concept: 'ability',
    modalFamily: 'past_ability',
    clueQuestion: 'Is this a skill in the past?',
    meaningHint: 'This is past ability. Use could.',
    tags: ['modal', 'could', 'past_ability'],
    difficulty: 2
  },
  {
    id: 'modal-009',
    game: 'modalDetective',
    sentence: '___ I open the window, please?',
    clueText: 'please',
    answer: 'can',
    acceptedAnswers: ['can', 'may'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'The speaker is asking permission. Can is normal permission; may is more formal.',
    concept: 'permission',
    modalFamily: 'permission',
    clueQuestion: 'Is someone asking if it is allowed?',
    meaningHint: 'This is permission. Use can or may.',
    tags: ['modal', 'can', 'may', 'permission'],
    difficulty: 1
  },
  {
    id: 'modal-010',
    game: 'modalDetective',
    sentence: '___ I come in, teacher?',
    clueText: 'teacher',
    answer: 'may',
    acceptedAnswers: ['may', 'can'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'The speaker asks a teacher for permission. May is polite and formal.',
    concept: 'permission',
    modalFamily: 'permission',
    clueQuestion: 'Is someone asking permission politely?',
    meaningHint: 'This is polite permission. Use may.',
    tags: ['modal', 'may', 'permission', 'polite'],
    difficulty: 1
  },
  {
    id: 'modal-011',
    game: 'modalDetective',
    sentence: 'You ___ sit here if you want.',
    clueText: 'if you want',
    answer: 'can',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Someone is allowing the listener to sit here. Use can for permission.',
    concept: 'permission',
    modalFamily: 'permission',
    clueQuestion: 'Is someone allowed to do this?',
    meaningHint: 'This is permission. Use can.',
    tags: ['modal', 'can', 'permission'],
    difficulty: 1
  },
  {
    id: 'modal-012',
    game: 'modalDetective',
    sentence: 'Students ___ use the library after class.',
    clueText: 'use the library',
    answer: 'can',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'This tells what students are allowed to do. Use can for permission.',
    concept: 'permission',
    modalFamily: 'permission',
    clueQuestion: 'Are students allowed to do this?',
    meaningHint: 'This is permission. Use can.',
    tags: ['modal', 'can', 'permission'],
    difficulty: 2
  },
  {
    id: 'modal-013',
    game: 'modalDetective',
    sentence: '___ you help me with this box, please?',
    clueText: 'help me',
    answer: 'could',
    acceptedAnswers: ['could', 'can'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'The speaker is asking politely for help. Could makes the request polite.',
    concept: 'request',
    modalFamily: 'polite_request',
    clueQuestion: 'Is someone asking politely for help?',
    meaningHint: 'This is a polite request. Use could.',
    tags: ['modal', 'could', 'polite_request'],
    difficulty: 1
  },
  {
    id: 'modal-014',
    game: 'modalDetective',
    sentence: '___ I borrow your eraser, please?',
    clueText: 'borrow your eraser',
    answer: 'could',
    acceptedAnswers: ['could', 'can', 'may'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Borrowing is a request. Could is the polite choice.',
    concept: 'request',
    modalFamily: 'polite_request',
    clueQuestion: 'Is someone asking politely to borrow something?',
    meaningHint: 'This is a polite request. Use could.',
    tags: ['modal', 'could', 'polite_request'],
    difficulty: 1
  },
  {
    id: 'modal-015',
    game: 'modalDetective',
    sentence: '___ you speak more slowly, please?',
    clueText: 'please',
    answer: 'could',
    acceptedAnswers: ['could', 'can'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'The speaker is politely asking someone to do something. Use could.',
    concept: 'request',
    modalFamily: 'polite_request',
    clueQuestion: 'Is this a polite request?',
    meaningHint: 'This is a polite request. Use could.',
    tags: ['modal', 'could', 'polite_request'],
    difficulty: 2
  },
  {
    id: 'modal-016',
    game: 'modalDetective',
    sentence: '___ you pass me the salt?',
    clueText: 'pass me the salt',
    answer: 'could',
    acceptedAnswers: ['could', 'can'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'The speaker wants someone to help. Could is polite for requests.',
    concept: 'request',
    modalFamily: 'polite_request',
    clueQuestion: 'Is someone asking for help politely?',
    meaningHint: 'This is a polite request. Use could.',
    tags: ['modal', 'could', 'polite_request'],
    difficulty: 2
  },
  {
    id: 'modal-017',
    game: 'modalDetective',
    sentence: 'She ___ be at home, but I am not sure.',
    clueText: 'not sure',
    answer: 'might',
    acceptedAnswers: ['might', 'may', 'could'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Not sure means maybe. Use might, may, or could for possibility.',
    concept: 'possibility',
    modalFamily: 'possibility',
    clueQuestion: 'Are we guessing because we are not sure?',
    meaningHint: 'This is possibility. Use may, might, or could.',
    tags: ['modal', 'might', 'may', 'could', 'possibility'],
    difficulty: 1
  },
  {
    id: 'modal-018',
    game: 'modalDetective',
    sentence: 'It is cloudy, so it ___ rain later.',
    clueText: 'cloudy',
    answer: 'may',
    acceptedAnswers: ['may', 'might', 'could'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Clouds make rain possible, but not certain. Use may, might, or could.',
    concept: 'possibility',
    modalFamily: 'possibility',
    clueQuestion: 'Is the speaker saying maybe?',
    meaningHint: 'This is possibility. Use may, might, or could.',
    tags: ['modal', 'may', 'might', 'could', 'possibility'],
    difficulty: 1
  },
  {
    id: 'modal-019',
    game: 'modalDetective',
    sentence: 'The answer ___ be B, but I need to check.',
    clueText: 'need to check',
    answer: 'might',
    acceptedAnswers: ['might', 'may', 'could'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Need to check means the speaker is not certain. Use might, may, or could.',
    concept: 'possibility',
    modalFamily: 'possibility',
    clueQuestion: 'Is the speaker uncertain?',
    meaningHint: 'This is possibility. Use may, might, or could.',
    tags: ['modal', 'might', 'possibility'],
    difficulty: 2
  },
  {
    id: 'modal-020',
    game: 'modalDetective',
    sentence: 'The baby ___ be hungry because she is crying.',
    clueText: 'because she is crying',
    answer: 'may',
    acceptedAnswers: ['may', 'might', 'could'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Crying is a clue, but we are not one hundred percent sure. Use may, might, or could.',
    concept: 'possibility',
    modalFamily: 'possibility',
    clueQuestion: 'Are we guessing from a clue?',
    meaningHint: 'This is possibility. Use may, might, or could.',
    tags: ['modal', 'may', 'possibility', 'evidence_guess'],
    difficulty: 2
  },
  {
    id: 'modal-021',
    game: 'modalDetective',
    sentence: 'He ___ come to the party, but he is still sick.',
    clueText: 'still sick',
    answer: 'might',
    acceptedAnswers: ['might', 'may', 'could'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'He is sick, so coming is uncertain. Use might, may, or could.',
    concept: 'possibility',
    modalFamily: 'possibility',
    clueQuestion: 'Is the future uncertain?',
    meaningHint: 'This is possibility. Use may, might, or could.',
    tags: ['modal', 'might', 'possibility'],
    difficulty: 2
  },
  {
    id: 'modal-022',
    game: 'modalDetective',
    sentence: 'Perhaps we ___ find the lost dog near the park.',
    clueText: 'Perhaps',
    answer: 'could',
    acceptedAnswers: ['could', 'may', 'might'],
    options: ['can', 'could', 'may', 'might'],
    explanation: 'Perhaps means maybe. Use could, may, or might for possibility.',
    concept: 'possibility',
    modalFamily: 'possibility',
    clueQuestion: 'Does the clue mean maybe?',
    meaningHint: 'This is possibility. Use could, may, or might.',
    tags: ['modal', 'could', 'possibility'],
    difficulty: 2
  },
  {
    id: 'modal-023',
    game: 'modalDetective',
    sentence: 'If you are bored, you ___ read a comic book.',
    clueText: 'If you are bored',
    answer: 'could',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'This gives one possible idea. Use could for a suggestion.',
    concept: 'suggestion',
    modalFamily: 'suggestion',
    clueQuestion: 'Is this one possible idea?',
    meaningHint: 'This is a suggestion. Use could.',
    tags: ['modal', 'could', 'suggestion'],
    difficulty: 1
  },
  {
    id: 'modal-024',
    game: 'modalDetective',
    sentence: 'We ___ make a card for Mom.',
    clueText: 'make a card',
    answer: 'could',
    options: ['can', 'could', 'may', 'might'],
    explanation: 'This is one possible idea for what to do. Use could for a suggestion.',
    concept: 'suggestion',
    modalFamily: 'suggestion',
    clueQuestion: 'Is this a suggested idea?',
    meaningHint: 'This is a suggestion. Use could.',
    tags: ['modal', 'could', 'suggestion'],
    difficulty: 1
  },

  // ==========================================
  // ACTION FREEZE DETECTIVE (18 questions)
  // ==========================================
  {
    id: 'freeze-001',
    game: 'actionFreezeDetective',
    sentence: 'I ___ TV when the phone rang.',
    clueText: 'when',
    answer: 'was watching',
    options: ['watched', 'was watching', 'were watching', 'am watching'],
    explanation: 'The long action "was watching" was interrupted "when" the phone rang.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'when'],
    difficulty: 1,
    subject: 'I',
    baseVerb: 'watch',
    longAction: 'watch TV',
    interruptingAction: 'phone rang',
    auxiliary: 'was'
  },
  {
    id: 'freeze-002',
    game: 'actionFreezeDetective',
    sentence: 'While we ___, it started to rain.',
    clueText: 'While',
    answer: 'were playing',
    options: ['played', 'were playing', 'was playing', 'are playing'],
    explanation: '"While" shows a long background action. Use "were playing" for "we".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while', 'subject_agreement'],
    difficulty: 1,
    subject: 'we',
    baseVerb: 'play',
    longAction: 'play',
    interruptingAction: 'started to rain',
    auxiliary: 'were'
  },
  {
    id: 'freeze-003',
    game: 'actionFreezeDetective',
    sentence: 'She ___ her bike at 5 PM yesterday.',
    clueText: 'at 5 PM yesterday',
    answer: 'was riding',
    options: ['rode', 'was riding', 'were riding', 'is riding'],
    explanation: 'An exact time in the past shows an action in progress. Use "was riding".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'exact_time'],
    difficulty: 2,
    subject: 'She',
    baseVerb: 'ride',
    longAction: 'ride her bike',
    auxiliary: 'was'
  },
  {
    id: 'freeze-004',
    game: 'actionFreezeDetective',
    sentence: 'They ___ dinner when the lights went out.',
    clueText: 'when',
    answer: 'were eating',
    options: ['ate', 'was eating', 'were eating', 'eat'],
    explanation: 'The long action "were eating" was interrupted. Use "were" for "They".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'subject_agreement'],
    difficulty: 1,
    subject: 'They',
    baseVerb: 'eat',
    longAction: 'eat dinner',
    interruptingAction: 'lights went out',
    auxiliary: 'were'
  },
  {
    id: 'freeze-005',
    game: 'actionFreezeDetective',
    sentence: 'While he ___ a book, his sister was listening to music.',
    clueText: 'While',
    answer: 'was reading',
    options: ['read', 'was reading', 'were reading', 'reads'],
    explanation: 'Two long actions happening at the same time. Use "was reading" for "he".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'parallel_actions'],
    difficulty: 2,
    subject: 'he',
    baseVerb: 'read',
    longAction: 'read a book',
    auxiliary: 'was'
  },
  {
    id: 'freeze-006',
    game: 'actionFreezeDetective',
    sentence: 'You ___ too fast when the police stopped you.',
    clueText: 'when',
    answer: 'were driving',
    options: ['drove', 'was driving', 'were driving', 'drive'],
    explanation: 'The driving was interrupted. Use "were driving" with "You".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'subject_agreement'],
    difficulty: 2,
    subject: 'You',
    baseVerb: 'drive',
    longAction: 'drive too fast',
    interruptingAction: 'police stopped',
    auxiliary: 'were'
  },
  {
    id: 'freeze-007',
    game: 'actionFreezeDetective',
    sentence: 'I dropped my keys while I ___ to the bus stop.',
    clueText: 'while',
    answer: 'was walking',
    options: ['walked', 'was walking', 'were walking', 'am walking'],
    explanation: 'The walking was the long action happening when the keys dropped.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'while'],
    difficulty: 1,
    subject: 'I',
    baseVerb: 'walk',
    longAction: 'walk to the bus stop',
    interruptingAction: 'dropped my keys',
    auxiliary: 'was'
  },
  {
    id: 'freeze-008',
    game: 'actionFreezeDetective',
    sentence: 'You ___ at 8 o\'clock last night.',
    clueText: 'at 8 o\'clock',
    answer: 'were studying',
    options: ['studied', 'was studying', 'were studying', 'are studying'],
    explanation: 'Asking about an action in progress at a specific past time. Use "were studying".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'exact_time'],
    difficulty: 3,
    subject: 'you',
    baseVerb: 'study',
    longAction: 'study',
    auxiliary: 'were'
  },
  {
    id: 'freeze-009',
    game: 'actionFreezeDetective',
    sentence: 'The dog ___ loudly when someone knocked on the door.',
    clueText: 'when',
    answer: 'was barking',
    options: ['barked', 'was barking', 'were barking', 'barks'],
    explanation: 'The long action of barking was interrupted by the knock.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption'],
    difficulty: 1,
    subject: 'The dog',
    baseVerb: 'bark',
    longAction: 'bark loudly',
    interruptingAction: 'knocked',
    auxiliary: 'was'
  },
  {
    id: 'freeze-010',
    game: 'actionFreezeDetective',
    sentence: 'While the teacher ___, the students were taking notes.',
    clueText: 'While',
    answer: 'was speaking',
    options: ['spoke', 'was speaking', 'were speaking', 'speaks'],
    explanation: 'Two long actions at the same time. The teacher (singular) uses "was".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'parallel_actions'],
    difficulty: 2,
    subject: 'teacher',
    baseVerb: 'speak',
    longAction: 'speak',
    auxiliary: 'was'
  },
  {
    id: 'freeze-011',
    game: 'actionFreezeDetective',
    sentence: 'We ___ for the bus when it started to snow.',
    clueText: 'when',
    answer: 'were waiting',
    options: ['waited', 'was waiting', 'were waiting', 'wait'],
    explanation: 'Waiting is the long background action. "We" uses "were waiting".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption', 'subject_agreement'],
    difficulty: 1,
    subject: 'We',
    baseVerb: 'wait',
    longAction: 'wait for the bus',
    interruptingAction: 'started to snow',
    auxiliary: 'were'
  },
  {
    id: 'freeze-012',
    game: 'actionFreezeDetective',
    sentence: 'He broke his leg while he ___ football.',
    clueText: 'while',
    answer: 'was playing',
    options: ['played', 'was playing', 'were playing', 'is playing'],
    explanation: 'Playing football was the long action that got interrupted.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while', 'interruption'],
    difficulty: 1,
    subject: 'he',
    baseVerb: 'play',
    longAction: 'play football',
    interruptingAction: 'broke his leg',
    auxiliary: 'was'
  },
  {
    id: 'freeze-013',
    game: 'actionFreezeDetective',
    sentence: 'My friends ___ a movie when I arrived.',
    clueText: 'when',
    answer: 'were watching',
    options: ['watched', 'was watching', 'were watching', 'are watching'],
    explanation: '"Friends" is plural, so use "were watching" as the background action.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'subject_agreement', 'interruption'],
    difficulty: 2,
    subject: 'friends',
    baseVerb: 'watch',
    longAction: 'watch a movie',
    interruptingAction: 'arrived',
    auxiliary: 'were'
  },
  {
    id: 'freeze-014',
    game: 'actionFreezeDetective',
    sentence: 'At midnight, everyone ___ deeply.',
    clueText: 'At midnight',
    answer: 'was sleeping',
    options: ['slept', 'was sleeping', 'were sleeping', 'sleeps'],
    explanation: '"Everyone" takes a singular verb. The specific time indicates an action in progress.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'exact_time', 'subject_agreement'],
    difficulty: 3,
    subject: 'everyone',
    baseVerb: 'sleep',
    longAction: 'sleep deeply',
    auxiliary: 'was'
  },
  {
    id: 'freeze-015',
    game: 'actionFreezeDetective',
    sentence: 'While I was cooking, my brother ___ the table.',
    clueText: 'While',
    answer: 'was setting',
    options: ['set', 'was setting', 'were setting', 'sets'],
    explanation: 'Parallel actions happening at the same time in the past.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'parallel_actions'],
    difficulty: 2,
    subject: 'brother',
    baseVerb: 'set',
    longAction: 'set the table',
    auxiliary: 'was'
  },
  {
    id: 'freeze-016',
    game: 'actionFreezeDetective',
    sentence: 'The baby started crying while they ___ outside.',
    clueText: 'while',
    answer: 'were talking',
    options: ['talked', 'was talking', 'were talking', 'are talking'],
    explanation: 'The talking was the continuous action. "They" uses "were".',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while', 'subject_agreement'],
    difficulty: 1,
    subject: 'they',
    baseVerb: 'talk',
    longAction: 'talk outside',
    interruptingAction: 'baby started crying',
    auxiliary: 'were'
  },
  {
    id: 'freeze-017',
    game: 'actionFreezeDetective',
    sentence: 'I saw an accident while I ___ my car.',
    clueText: 'while',
    answer: 'was driving',
    options: ['drove', 'was driving', 'were driving', 'am driving'],
    explanation: 'Driving is the long background action.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'while'],
    difficulty: 1,
    subject: 'I',
    baseVerb: 'drive',
    longAction: 'drive my car',
    interruptingAction: 'saw an accident',
    auxiliary: 'was'
  },
  {
    id: 'freeze-018',
    game: 'actionFreezeDetective',
    sentence: 'She ___ her hair when the power went out.',
    clueText: 'when',
    answer: 'was drying',
    options: ['dried', 'was drying', 'were drying', 'dries'],
    explanation: 'The long action of drying hair was interrupted.',
    concept: 'past_continuous',
    tags: ['past_continuous', 'interruption'],
    difficulty: 1,
    subject: 'She',
    baseVerb: 'dry',
    longAction: 'dry her hair',
    interruptingAction: 'power went out',
    auxiliary: 'was'
  },

  // ==========================================
  // FUTURE FORECAST DETECTIVE (18 questions)
  // ==========================================
  {
    id: 'future-001',
    game: 'futureForecastDetective',
    sentence: 'Look at those dark clouds! It ___ rain.',
    clueText: 'dark clouds',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Dark clouds are visible evidence. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 1,
    futureUse: 'visible_evidence',
    subject: 'It',
    auxiliary: 'is'
  },
  {
    id: 'future-002',
    game: 'futureForecastDetective',
    sentence: 'I promise I ___ help you with your homework tonight.',
    clueText: 'promise',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'For a promise, use "will".',
    concept: 'future_forms',
    tags: ['future', 'promise', 'will'],
    difficulty: 1,
    futureUse: 'promise',
    subject: 'I'
  },
  {
    id: 'future-003',
    game: 'futureForecastDetective',
    sentence: 'We have bought the tickets. We ___ fly to Japan next week.',
    clueText: 'bought the tickets',
    answer: 'are going to',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'Having tickets means it is a firm plan. Use "are going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'We',
    auxiliary: 'are'
  },
  {
    id: 'future-004',
    game: 'futureForecastDetective',
    sentence: 'Oh, you dropped your pen. I ___ pick it up for you.',
    clueText: 'dropped your pen',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a quick decision or an offer to help right now. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'quick_decision', 'offer', 'will'],
    difficulty: 2,
    futureUse: 'quick_decision',
    subject: 'I'
  },
  {
    id: 'future-005',
    game: 'futureForecastDetective',
    sentence: 'I think that team ___ win the match today.',
    clueText: 'think',
    answer: 'will',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: '"I think" shows it is an opinion or guess. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'opinion', 'will'],
    difficulty: 1,
    futureUse: 'opinion',
    subject: 'team'
  },
  {
    id: 'future-006',
    game: 'futureForecastDetective',
    sentence: 'She packed her bags because she ___ stay at her grandma\'s house.',
    clueText: 'packed her bags',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Packing bags shows it is a plan. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'she',
    auxiliary: 'is'
  },
  {
    id: 'future-007',
    game: 'futureForecastDetective',
    sentence: 'Watch out! That glass ___ fall off the table!',
    clueText: 'Watch out',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: '"Watch out" means there is immediate visible danger. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 2,
    futureUse: 'visible_evidence',
    subject: 'glass',
    auxiliary: 'is'
  },
  {
    id: 'future-008',
    game: 'futureForecastDetective',
    sentence: 'I am thirsty. I ___ get a glass of water.',
    clueText: 'am thirsty',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a sudden decision made right now. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'quick_decision', 'will'],
    difficulty: 1,
    futureUse: 'quick_decision',
    subject: 'I'
  },
  {
    id: 'future-009',
    game: 'futureForecastDetective',
    sentence: 'We booked a table at the restaurant. We ___ have a family dinner.',
    clueText: 'booked a table',
    answer: 'are going to',
    options: ['will', 'are going to', 'is going to', 'am going to'],
    explanation: 'Booking a table makes it a set plan. Use "are going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'We',
    auxiliary: 'are'
  },
  {
    id: 'future-010',
    game: 'futureForecastDetective',
    sentence: 'Maybe I ___ visit my cousins next summer.',
    clueText: 'Maybe',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: '"Maybe" shows it is just an idea, not a firm plan yet. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'opinion', 'will'],
    difficulty: 2,
    futureUse: 'opinion',
    subject: 'I'
  },
  {
    id: 'future-011',
    game: 'futureForecastDetective',
    sentence: 'The sky is completely clear. It ___ be a beautiful day.',
    clueText: 'completely clear',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'A clear sky is strong evidence. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 2,
    futureUse: 'visible_evidence',
    subject: 'It',
    auxiliary: 'is'
  },
  {
    id: 'future-012',
    game: 'futureForecastDetective',
    sentence: 'Don\'t worry, I ___ not tell anyone your secret.',
    clueText: 'Don\'t worry',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a promise to keep a secret. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'promise', 'will'],
    difficulty: 1,
    futureUse: 'promise',
    subject: 'I'
  },
  {
    id: 'future-013',
    game: 'futureForecastDetective',
    sentence: 'Are you cold? I ___ close the window for you.',
    clueText: 'Are you cold',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a quick offer to help. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'offer', 'will'],
    difficulty: 2,
    futureUse: 'quick_decision',
    subject: 'I'
  },
  {
    id: 'future-014',
    game: 'futureForecastDetective',
    sentence: 'My brother bought flour and eggs. He ___ bake a cake.',
    clueText: 'bought flour',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Buying ingredients is a clear plan to bake. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'evidence', 'going_to'],
    difficulty: 2,
    futureUse: 'plan',
    subject: 'He',
    auxiliary: 'is'
  },
  {
    id: 'future-015',
    game: 'futureForecastDetective',
    sentence: 'In the year 2050, I believe people ___ live on Mars.',
    clueText: 'I believe',
    answer: 'will',
    options: ['will', 'are going to', 'is going to', 'am going to'],
    explanation: '"I believe" shows it is an opinion about the distant future. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'opinion', 'will'],
    difficulty: 2,
    futureUse: 'opinion',
    subject: 'people'
  },
  {
    id: 'future-016',
    game: 'futureForecastDetective',
    sentence: 'Look! The runner is way ahead of the others. He ___ win the race.',
    clueText: 'way ahead',
    answer: 'is going to',
    options: ['will', 'is going to', 'am going to', 'are going to'],
    explanation: 'Being way ahead is strong visible evidence right now. Use "is going to".',
    concept: 'future_forms',
    tags: ['future', 'evidence', 'going_to'],
    difficulty: 3,
    futureUse: 'visible_evidence',
    subject: 'He',
    auxiliary: 'is'
  },
  {
    id: 'future-017',
    game: 'futureForecastDetective',
    sentence: 'I ___ study medicine at university when I grow up. That is my dream.',
    clueText: 'my dream',
    answer: 'am going to',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'A strong life ambition or plan takes "going to". Use "am going to" for "I".',
    concept: 'future_forms',
    tags: ['future', 'plan', 'going_to'],
    difficulty: 3,
    futureUse: 'plan',
    subject: 'I',
    auxiliary: 'am'
  },
  {
    id: 'future-018',
    game: 'futureForecastDetective',
    sentence: 'The phone is ringing! I ___ answer it.',
    clueText: 'is ringing',
    answer: 'will',
    options: ['will', 'am going to', 'is going to', 'are going to'],
    explanation: 'This is a quick decision made at the moment of speaking. Use "will".',
    concept: 'future_forms',
    tags: ['future', 'quick_decision', 'will'],
    difficulty: 1,
    futureUse: 'quick_decision',
    subject: 'I'
  }
];
