module.exports = [
  {
    chapterNumber: 1,
    chapterId: 'chapter_01',
    title: 'The Boy Who Lived',
    dateLabel: '1 November 1981',
    sourceHeadings: ['CHAPTER ONE', 'THE BOY WHO LIVED'],
  },
  {
    chapterNumber: 2,
    chapterId: 'chapter_02',
    title: 'The Vanishing Glass',
    dateLabel: '23 June 1991',
    sourceHeadings: ['CHAPTER TWO', 'THE VANISHING GLASS'],
  },
  {
    chapterNumber: 3,
    chapterId: 'chapter_03',
    title: 'The Letters from No One',
    dateLabel: '23 July 1991',
    sourceHeadings: ['CHAPTER THREE', 'THE LETTERS FROM NO ONE'],
  },
  {
    chapterNumber: 4,
    chapterId: 'chapter_04',
    title: 'The Keeper of the Keys',
    dateLabel: '31 July 1991',
    sourceHeadings: ['CHAPTER FOUR', 'THE KEEPER OF THE KEYS'],
  },
  {
    chapterNumber: 5,
    chapterId: 'chapter_05',
    title: 'Diagon Alley',
    dateLabel: '31 July 1991',
    sourceHeadings: ['CHAPTER FIVE', 'DIAGON ALLEY'],
  },
  {
    chapterNumber: 6,
    chapterId: 'chapter_06',
    title: 'The Journey from Platform Nine and Three-Quarters',
    dateLabel: '1 August 1991',
    sourceHeadings: ['CHAPTER SIX', 'THE JOURNEY FROM PLATFORM NINE AND THREE-QUARTERS'],
  },
  {
    chapterNumber: 7,
    chapterId: 'chapter_07',
    title: 'The Sorting Hat',
    dateLabel: '1 September 1991',
    sourceHeadings: ['CHAPTER SEVEN', 'THE SORTING HAT'],
  },
  {
    chapterNumber: 8,
    chapterId: 'chapter_08',
    title: 'The Potions Master',
    dateLabel: '2 September 1991',
    sourceHeadings: ['CHAPTER EIGHT', 'THE POTIONS MASTER'],
  },
  {
    chapterNumber: 9,
    chapterId: 'chapter_09',
    title: 'The Midnight Duel',
    dateLabel: '12 September 1991',
    sourceHeadings: ['CHAPTER NINE', 'THE MIDNIGHT DUEL'],
  },
  {
    chapterNumber: 10,
    chapterId: 'chapter_10',
    title: "Hallowe'en",
    dateLabel: '13 September 1991',
    sourceHeadings: ['CHAPTER TEN', 'HALLOWEEN', "HALLOWE'EN"],
  },
  {
    chapterNumber: 11,
    chapterId: 'chapter_11',
    title: 'Quidditch',
    dateLabel: '8 November 1991',
    sourceHeadings: ['CHAPTER ELEVEN', 'QUIDDITCH'],
  },
  {
    chapterNumber: 12,
    chapterId: 'chapter_12',
    title: 'The Mirror of Erised',
    dateLabel: '21 December 1991',
    sourceHeadings: ['CHAPTER TWELVE', 'THE MIRROR OF ERISED'],
  },
  {
    chapterNumber: 13,
    chapterId: 'chapter_13',
    title: 'Nicolas Flamel',
    dateLabel: '5 January 1992',
    sourceHeadings: ['CHAPTER THIRTEEN', 'NICOLAS FLAMEL'],
  },
  {
    chapterNumber: 14,
    chapterId: 'chapter_14',
    title: 'Norbert the Norwegian Ridgeback',
    dateLabel: '23 March 1992',
    sourceHeadings: ['CHAPTER FOURTEEN', 'NORBERT THE NORWEGIAN RIDGEBACK'],
  },
  {
    chapterNumber: 15,
    chapterId: 'chapter_15',
    title: 'The Forbidden Forest',
    dateLabel: '10 May 1992',
    sourceHeadings: ['CHAPTER FIFTEEN', 'THE FORBIDDEN FOREST'],
  },
  {
    chapterNumber: 16,
    chapterId: 'chapter_16',
    title: 'Through the Trapdoor',
    dateLabel: '4 June 1992',
    sourceHeadings: ['CHAPTER SIXTEEN', 'THROUGH THE TRAPDOOR'],
  },
  {
    chapterNumber: 17,
    chapterId: 'chapter_17',
    title: 'The Man with Two Faces',
    dateLabel: '4 June 1992',
    sourceHeadings: ['CHAPTER SEVENTEEN', 'THE MAN WITH TWO FACES'],
  },
];
